import { InstallationModelPagedResult, AppSummaryModelPagedResult } from '@reapit/foundations-ts-definitions'

export const stubInstallations: InstallationModelPagedResult = {
  data: [
    {
      id: '0c2fc189-e233-407a-b86b-0f9081e0d21c',
      appId: 'dab46391-b07d-4869-8614-139aa798cc1f',
      created: '2020-12-02T17:48:49',
      client: 'SBOX',
      status: 'Active',
      authFlow: 'authorisationCode',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/0c2fc189-e233-407a-b86b-0f9081e0d21c',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/dab46391-b07d-4869-8614-139aa798cc1f',
          action: 'GET',
        },
      ],
    },
    {
      id: 'dc235b02-2414-4a5f-8460-6e55c179ee9a',
      appId: 'cfbe6f29-4003-4648-aa5a-8eb777bd606e',
      created: '2020-12-02T17:46:11',
      client: 'SBOX',
      status: 'Active',
      authFlow: 'authorisationCode',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/dc235b02-2414-4a5f-8460-6e55c179ee9a',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/cfbe6f29-4003-4648-aa5a-8eb777bd606e',
          action: 'GET',
        },
      ],
    },
    {
      id: '4f718cfe-34a6-4efb-a72f-f52dc8fd7368',
      appId: '795fc578-8232-4dbd-a5ff-1240135c0a52',
      created: '2020-12-02T08:21:53',
      client: 'SBOX',
      status: 'Active',
      authFlow: 'authorisationCode',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/4f718cfe-34a6-4efb-a72f-f52dc8fd7368',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/795fc578-8232-4dbd-a5ff-1240135c0a52',
          action: 'GET',
        },
      ],
    },
    {
      id: 'b321559f-c7c5-4969-9238-f6ebcb5490dd',
      appId: 'a2b9c6f6-0e53-4fcf-a095-be8cc18482b3',
      created: '2020-12-01T17:02:08',
      client: 'SBOX',
      status: 'Active',
      authFlow: 'authorisationCode',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/b321559f-c7c5-4969-9238-f6ebcb5490dd',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/a2b9c6f6-0e53-4fcf-a095-be8cc18482b3',
          action: 'GET',
        },
      ],
    },
    {
      id: '6afaea8d-d0e2-4c90-91a9-c75e32e323ef',
      appId: '6b213889-d61b-4a56-9f40-56826b420dee',
      created: '2020-12-01T16:05:52',
      client: 'SBOX',
      status: 'Active',
      authFlow: 'clientCredentials',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/6afaea8d-d0e2-4c90-91a9-c75e32e323ef',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/6b213889-d61b-4a56-9f40-56826b420dee',
          action: 'GET',
        },
      ],
    },
    {
      id: '5b925dd3-c0a0-4194-8c27-434a662e10da',
      appId: '06ae7f8e-7a01-4b29-9049-1fd86e3ec52b',
      created: '2020-12-02T15:00:23',
      client: 'SBOX',
      status: 'Active',
      authFlow: 'authorisationCode',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/5b925dd3-c0a0-4194-8c27-434a662e10da',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/06ae7f8e-7a01-4b29-9049-1fd86e3ec52b',
          action: 'GET',
        },
      ],
    },
    {
      id: '805d0cb6-ab51-463b-87c1-6163faaee3fd',
      appId: '98a906fd-541b-4f3c-8bab-44f84dd528be',
      created: '2020-12-03T08:32:35',
      client: 'SBOX',
      status: 'Terminated',
      authFlow: 'clientCredentials',
      terminatedReason: 'User uninstall',
      terminatesOn: '2020-12-03T08:32:46',
      customerId: 'SBOX',
      customerName: 'Sandbox Estates',
      customerAddress: {
        buildingName: 'Third Floor',
        buildingNumber: '67-74',
        line1: 'Saffron Hill',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'EC1N 8QX',
        countryId: 'GB',
      },
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations/805d0cb6-ab51-463b-87c1-6163faaee3fd',
          action: 'GET',
        },
        {
          rel: 'app',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/98a906fd-541b-4f3c-8bab-44f84dd528be',
          action: 'GET',
        },
      ],
    },
  ],
  pageNumber: 1,
  pageSize: 9999,
  pageCount: 7,
  totalCount: 7,
}

export const stubAppsList: AppSummaryModelPagedResult = {
  data: [
    {
      id: '795fc578-8232-4dbd-a5ff-1240135c0a52',
      externalId: '7dim9s02ifbq623k4d0vk91tgl',
      created: '2020-11-05T08:59:14',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Reapit Payments Portal',
      summary: '',
      developer: 'Reapit Ltd',
      homePage: '',
      isListed: false,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Payments-Portal-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Payments-Portal-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['Property'],
      authFlow: 'code',
      launchUri: 'https://payments.dev.paas.reapit.cloud/payments',
      pendingRevisions: false,
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/795fc578-8232-4dbd-a5ff-1240135c0a52',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: '06ae7f8e-7a01-4b29-9049-1fd86e3ec52b',
      externalId: '5dk5afvtj04tmdlmt4i3aipjk0',
      created: '2020-11-05T08:56:39',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Data Warehouse',
      summary: 'The data warehouse houses lots of data. The data warehouse houses lots of data.',
      developer: 'Reapit Ltd',
      homePage: 'https://data-warehouse-app.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: false,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Data-Warehouse-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Data-Warehouse-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      authFlow: 'code',
      launchUri: 'https://data-warehouse-app.dev.paas.reapit.cloud/login',
      pendingRevisions: false,
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/06ae7f8e-7a01-4b29-9049-1fd86e3ec52b',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'a2b9c6f6-0e53-4fcf-a095-be8cc18482b3',
      externalId: '4m6mr1t2d0si3pfl4rludmqei1',
      created: '2020-11-05T08:48:44',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Reapit Connect',
      summary:
        'Reapit Connect removes the overhead of having to build and maintain a user credential directory for your app.',
      developer: 'Reapit Ltd',
      homePage: 'https://reapit-connect.dev.paas.reapit.cloud/welcome',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: true,
      isFree: false,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Connect-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Connect-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      authFlow: 'code',
      launchUri: 'https://reapit-connect.dev.paas.reapit.cloud/welcome',
      pendingRevisions: false,
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/a2b9c6f6-0e53-4fcf-a095-be8cc18482b3',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'dab46391-b07d-4869-8614-139aa798cc1f',
      externalId: '7gvr744qtpqn2batr1hc8hie0c',
      created: '2020-11-04T17:11:40',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Online Check List',
      summary:
        'Helps you to get organised, simplify your workflow, and to ensure checks are carried out. Manage your checks online from anywhere.',
      developer: 'Reapit Ltd',
      homePage: 'https://aml-app.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Online-Check-List-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Online-Check-List-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['IdCheck'],
      authFlow: 'code',
      launchUri: 'https://aml-app.dev.paas.reapit.cloud',
      pendingRevisions: false,
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/dab46391-b07d-4869-8614-139aa798cc1f',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'cfbe6f29-4003-4648-aa5a-8eb777bd606e',
      externalId: '4kr750gbarufkanl2ceasofmpk',
      created: '2020-11-04T17:02:47',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Geo Diary',
      summary: 'GEO Diary is the App for the Negotiator on the go, instant access to your daily & weekly appointments',
      developer: 'Reapit Ltd',
      homePage: 'https://geo-diary-app.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['Property', 'Applicant'],
      authFlow: 'code',
      launchUri: 'https://geo-diary-app.dev.paas.reapit.cloud',
      pendingRevisions: false,
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/cfbe6f29-4003-4648-aa5a-8eb777bd606e',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
  ],
  pageNumber: 1,
  pageSize: 9999,
  pageCount: 5,
  totalCount: 5,
}
