import { PagedResultContactModel_ } from '@reapit/foundations-ts-definitions'

export const contacts = {
  _embedded: [
    {
      id: 'MKC16000007',
      created: '2019-03-27T12:31:21.0000000Z',
      modified: '2020-01-14T09:55:50.0000000Z',
      title: 'Mr',
      forename: 'Carson',
      surname: 'Philip',
      dateOfBirth: '2019-11-22',
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'pending',
      source: '',
      homePhone: '01632 968347',
      workPhone: '020 7946 8347',
      mobilePhone: '07700 908347',
      email: 'cphilip133@rpsfiction.net',
      primaryAddress: {
        type: 'primary',
        buildingName: '123',
        buildingNumber: '1',
        line1: 'Harcourt Close',
        line2: 'Leighton Buzzard',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'LU7 2ST',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondaryy',
        buildingName: '123',
        buildingNumber: '1',
        line1: 'Harcourt Close',
        line2: 'Leighton Buzzard',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'LU7 2ST',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['MKC'],
      negotiatorIds: ['RMK'],
      metadata: {},
      _eTag: '"9CBE436919C6BE89A8642BC70A7CFAEE"',
      _links: {
        self: {
          href: '/contacts/MKC16000007',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=MKC16000007',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=MKC16000007',
        },
        offices: {
          href: '/offices/?id=MKC',
        },
        negotiators: {
          href: '/negotiators/?id=RMK',
        },
      },
      _embedded: {},
    },
    {
      id: 'BUC15000399',
      created: '2018-09-25T10:20:25.0000000Z',
      modified: '2019-12-30T08:46:21.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Strang',
      dateOfBirth: '2019-12-19',
      active: false,
      marketingConsent: 'notAsked',
      identityCheck: 'pending',
      source: '',
      homePhone: '123456789',
      workPhone: '1234566789',
      mobilePhone: '1234566789',
      email: '1234566789@gmail.com',
      primaryAddress: {
        type: 'primary',
        buildingName: 'The Wing',
        buildingNumber: '12313',
        line1: 'Little Tingewick',
        line2: 'Buckingham',
        line3: 'Buckinghamshire',
        line4: '123',
        postcode: 'MK18 4AG',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondaryy',
        buildingName: '123',
        buildingNumber: '123123',
        line1: '123123',
        line2: '123123',
        line3: '123123',
        line4: '123123',
        postcode: '123123',
        countryId: '',
      },
      workAddress: '',
      officeIds: ['BUC'],
      negotiatorIds: ['PAE'],
      metadata: {},
      _eTag: '"9CAAB45D503202CCFB0118261AB523CD"',
      _links: {
        self: {
          href: '/contacts/BUC15000399',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BUC15000399',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BUC15000399',
        },
        offices: {
          href: '/offices/?id=BUC',
        },
        negotiators: {
          href: '/negotiators/?id=PAE',
        },
      },
      _embedded: {},
    },
    {
      id: 'BUC15000351',
      created: '2018-08-25T07:58:42.0000000Z',
      modified: '2019-12-30T09:49:03.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Bruce',
      dateOfBirth: '2019-08-05',
      active: false,
      marketingConsent: 'notAsked',
      identityCheck: 'pending',
      source: '',
      homePhone: '123',
      workPhone: '123',
      mobilePhone: '123',
      email: 'abc@gmail.com',
      primaryAddress: {
        type: 'primary',
        buildingName: 'Field Farm House',
        buildingNumber: '123',
        line1: 'Field Farm Business Centre',
        line2: 'Launton',
        line3: 'Bicester',
        line4: 'Oxfordshire',
        postcode: 'OX26 5EL',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: '123',
        buildingNumber: '1',
        line1: 'Harcourt Close',
        line2: 'Leighton Buzzard',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'LU7 2ST',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['BUC'],
      negotiatorIds: ['FHA'],
      metadata: {},
      _eTag: '"CCF150645B4D3071950ABE946F2C48A5"',
      _links: {
        self: {
          href: '/contacts/BUC15000351',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BUC15000351',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BUC15000351',
        },
        offices: {
          href: '/offices/?id=BUC',
        },
        negotiators: {
          href: '/negotiators/?id=FHA',
        },
      },
      _embedded: {},
    },
    {
      id: 'BED14001610',
      created: '2018-01-12T16:04:05.0000000Z',
      modified: '2018-03-09T11:05:44.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Wilson',
      dateOfBirth: null,
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'unchecked',
      source: '',
      homePhone: '01632 970935',
      workPhone: '020 7946 1093',
      mobilePhone: '07700 910935',
      email: 'pwilson835@rpsfiction.net',
      primaryAddress: {
        type: 'home',
        buildingName: '',
        buildingNumber: '21',
        line1: 'Mayhew Close',
        line2: 'Bromham',
        line3: 'Bedfordshire',
        line4: '',
        postcode: 'MK43 8PW',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: 'The Brae',
        buildingNumber: '2',
        line1: 'West End Road',
        line2: 'Kempston',
        line3: 'Bedford',
        line4: 'Bedfordshire',
        postcode: 'MK43 8RT',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['BED'],
      negotiatorIds: ['AJS'],
      metadata: {},
      _eTag: '"17D851BF8B47F7EF8F3A2909414AB336"',
      _links: {
        self: {
          href: '/contacts/BED14001610',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BED14001610',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BED14001610',
        },
        offices: {
          href: '/offices/?id=BED',
        },
        negotiators: {
          href: '/negotiators/?id=AJS',
        },
      },
      _embedded: {},
    },
    {
      id: 'BED14000165',
      created: '2017-04-18T08:08:48.0000000Z',
      modified: '2017-08-24T09:34:27.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Grierson',
      dateOfBirth: null,
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'unchecked',
      source: '',
      homePhone: '01632 963820',
      workPhone: '020 7946 3820',
      mobilePhone: '07700 903820',
      email: 'pgrierson93@rpsfiction.net',
      primaryAddress: {
        type: 'home',
        buildingName: '',
        buildingNumber: '33',
        line1: 'Pemberley Avenue',
        line2: 'Bedford',
        line3: 'Bedfordshire',
        line4: '',
        postcode: 'MK40 2LE',
        countryId: '',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: '',
        buildingNumber: '28',
        line1: 'Greenvale Road',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'SE9 1PD',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['BED'],
      negotiatorIds: ['JJS'],
      metadata: {},
      _eTag: '"28DCEEC21FEEC6CCCF0E3D8A51DBBDDD"',
      _links: {
        self: {
          href: '/contacts/BED14000165',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BED14000165',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BED14000165',
        },
        offices: {
          href: '/offices/?id=BED',
        },
        negotiators: {
          href: '/negotiators/?id=JJS',
        },
      },
      _embedded: {},
    },
    {
      id: 'BED13001801',
      created: '2016-06-27T11:17:13.0000000Z',
      modified: '2019-10-31T08:38:01.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Shanks',
      dateOfBirth: null,
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'unchecked',
      source: '',
      homePhone: '01632 969249',
      workPhone: '020 7946 9249',
      mobilePhone: '07700 909249',
      email: 'pshanks304@rpsfiction.net',
      primaryAddress: {
        type: 'primary',
        buildingName: '',
        buildingNumber: '31',
        line1: 'Bower Street',
        line2: 'Bedford',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'MK40 3RD',
        countryId: '',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: '123123',
        buildingNumber: '2142314',
        line1: '21342134',
        line2: '21342134',
        line3: '2314132',
        line4: '21343214',
        postcode: '2341234',
        countryId: '',
      },
      workAddress: '',
      officeIds: ['BED'],
      negotiatorIds: ['MBW'],
      metadata: {},
      _eTag: '"E13FBA71A43612AE52F7CBF02C6DA0B6"',
      _links: {
        self: {
          href: '/contacts/BED13001801',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BED13001801',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BED13001801',
        },
        offices: {
          href: '/offices/?id=BED',
        },
        negotiators: {
          href: '/negotiators/?id=MBW',
        },
      },
      _embedded: {},
    },
  ],
  pageNumber: 1,
  pageSize: 10,
  pageCount: 6,
  totalCount: 6,
  _links: {
    self: {
      href: '/contacts/?PageNumber=1&PageSize=10&name=Philip',
    },
    first: {
      href: '/contacts/?PageNumber=1&PageSize=10&name=Philip',
    },
  },
} as PagedResultContactModel_

export const responseContactWithStatus = {
  _embedded: [
    {
      id: 'MKC16000007',
      created: '2019-03-27T12:31:21.0000000Z',
      modified: '2020-01-14T09:55:50.0000000Z',
      title: 'Mr',
      forename: 'Carson',
      surname: 'Philip',
      dateOfBirth: '2019-11-22',
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'pending',
      source: '',
      homePhone: '01632 968347',
      workPhone: '020 7946 8347',
      mobilePhone: '07700 908347',
      email: 'cphilip133@rpsfiction.net',
      primaryAddress: {
        type: 'primary',
        buildingName: '123',
        buildingNumber: '1',
        line1: 'Harcourt Close',
        line2: 'Leighton Buzzard',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'LU7 2ST',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondaryy',
        buildingName: '123',
        buildingNumber: '1',
        line1: 'Harcourt Close',
        line2: 'Leighton Buzzard',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'LU7 2ST',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['MKC'],
      negotiatorIds: ['RMK'],
      metadata: {},
      _eTag: '"9CBE436919C6BE89A8642BC70A7CFAEE"',
      _links: {
        self: {
          href: '/contacts/MKC16000007',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=MKC16000007',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=MKC16000007',
        },
        offices: {
          href: '/offices/?id=MKC',
        },
        negotiators: {
          href: '/negotiators/?id=RMK',
        },
      },
      _embedded: {},
    },
    {
      id: 'BUC15000399',
      created: '2018-09-25T10:20:25.0000000Z',
      modified: '2019-12-30T08:46:21.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Strang',
      dateOfBirth: '2019-12-19',
      active: false,
      marketingConsent: 'notAsked',
      identityCheck: 'pending',
      source: '',
      homePhone: '123456789',
      workPhone: '1234566789',
      mobilePhone: '1234566789',
      email: '1234566789@gmail.com',
      primaryAddress: {
        type: 'primary',
        buildingName: 'The Wing',
        buildingNumber: '12313',
        line1: 'Little Tingewick',
        line2: 'Buckingham',
        line3: 'Buckinghamshire',
        line4: '123',
        postcode: 'MK18 4AG',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondaryy',
        buildingName: '123',
        buildingNumber: '123123',
        line1: '123123',
        line2: '123123',
        line3: '123123',
        line4: '123123',
        postcode: '123123',
        countryId: '',
      },
      workAddress: '',
      officeIds: ['BUC'],
      negotiatorIds: ['PAE'],
      metadata: {},
      _eTag: '"9CAAB45D503202CCFB0118261AB523CD"',
      _links: {
        self: {
          href: '/contacts/BUC15000399',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BUC15000399',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BUC15000399',
        },
        offices: {
          href: '/offices/?id=BUC',
        },
        negotiators: {
          href: '/negotiators/?id=PAE',
        },
      },
      _embedded: {},
    },
    {
      id: 'BUC15000351',
      created: '2018-08-25T07:58:42.0000000Z',
      modified: '2019-12-30T09:49:03.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Bruce',
      dateOfBirth: '2019-08-05',
      active: false,
      marketingConsent: 'notAsked',
      identityCheck: 'pending',
      source: '',
      homePhone: '123',
      workPhone: '123',
      mobilePhone: '123',
      email: 'abc@gmail.com',
      primaryAddress: {
        type: 'primary',
        buildingName: 'Field Farm House',
        buildingNumber: '123',
        line1: 'Field Farm Business Centre',
        line2: 'Launton',
        line3: 'Bicester',
        line4: 'Oxfordshire',
        postcode: 'OX26 5EL',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: '123',
        buildingNumber: '1',
        line1: 'Harcourt Close',
        line2: 'Leighton Buzzard',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'LU7 2ST',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['BUC'],
      negotiatorIds: ['FHA'],
      metadata: {},
      _eTag: '"CCF150645B4D3071950ABE946F2C48A5"',
      _links: {
        self: {
          href: '/contacts/BUC15000351',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BUC15000351',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BUC15000351',
        },
        offices: {
          href: '/offices/?id=BUC',
        },
        negotiators: {
          href: '/negotiators/?id=FHA',
        },
      },
      _embedded: {},
    },
    {
      id: 'BED14001610',
      created: '2018-01-12T16:04:05.0000000Z',
      modified: '2018-03-09T11:05:44.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Wilson',
      dateOfBirth: null,
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'unchecked',
      source: '',
      homePhone: '01632 970935',
      workPhone: '020 7946 1093',
      mobilePhone: '07700 910935',
      email: 'pwilson835@rpsfiction.net',
      primaryAddress: {
        type: 'home',
        buildingName: '',
        buildingNumber: '21',
        line1: 'Mayhew Close',
        line2: 'Bromham',
        line3: 'Bedfordshire',
        line4: '',
        postcode: 'MK43 8PW',
        countryId: 'GB',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: 'The Brae',
        buildingNumber: '2',
        line1: 'West End Road',
        line2: 'Kempston',
        line3: 'Bedford',
        line4: 'Bedfordshire',
        postcode: 'MK43 8RT',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['BED'],
      negotiatorIds: ['AJS'],
      metadata: {},
      _eTag: '"17D851BF8B47F7EF8F3A2909414AB336"',
      _links: {
        self: {
          href: '/contacts/BED14001610',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BED14001610',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BED14001610',
        },
        offices: {
          href: '/offices/?id=BED',
        },
        negotiators: {
          href: '/negotiators/?id=AJS',
        },
      },
      _embedded: {},
    },
    {
      id: 'BED14000165',
      created: '2017-04-18T08:08:48.0000000Z',
      modified: '2017-08-24T09:34:27.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Grierson',
      dateOfBirth: null,
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'unchecked',
      source: '',
      homePhone: '01632 963820',
      workPhone: '020 7946 3820',
      mobilePhone: '07700 903820',
      email: 'pgrierson93@rpsfiction.net',
      primaryAddress: {
        type: 'home',
        buildingName: '',
        buildingNumber: '33',
        line1: 'Pemberley Avenue',
        line2: 'Bedford',
        line3: 'Bedfordshire',
        line4: '',
        postcode: 'MK40 2LE',
        countryId: '',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: '',
        buildingNumber: '28',
        line1: 'Greenvale Road',
        line2: 'London',
        line3: '',
        line4: '',
        postcode: 'SE9 1PD',
        countryId: 'GB',
      },
      workAddress: '',
      officeIds: ['BED'],
      negotiatorIds: ['JJS'],
      metadata: {},
      _eTag: '"28DCEEC21FEEC6CCCF0E3D8A51DBBDDD"',
      _links: {
        self: {
          href: '/contacts/BED14000165',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BED14000165',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BED14000165',
        },
        offices: {
          href: '/offices/?id=BED',
        },
        negotiators: {
          href: '/negotiators/?id=JJS',
        },
      },
      _embedded: {},
    },
    {
      id: 'BED13001801',
      created: '2016-06-27T11:17:13.0000000Z',
      modified: '2019-10-31T08:38:01.0000000Z',
      title: 'Mr',
      forename: 'Philip',
      surname: 'Shanks',
      dateOfBirth: null,
      active: true,
      marketingConsent: 'notAsked',
      identityCheck: 'unchecked',
      source: '',
      homePhone: '01632 969249',
      workPhone: '020 7946 9249',
      mobilePhone: '07700 909249',
      email: 'pshanks304@rpsfiction.net',
      primaryAddress: {
        type: 'primary',
        buildingName: '',
        buildingNumber: '31',
        line1: 'Bower Street',
        line2: 'Bedford',
        line3: 'Bedfordshire',
        line4: '123123',
        postcode: 'MK40 3RD',
        countryId: '',
      },
      secondaryAddress: {
        type: 'secondary',
        buildingName: '123123',
        buildingNumber: '2142314',
        line1: '21342134',
        line2: '21342134',
        line3: '2314132',
        line4: '21343214',
        postcode: '2341234',
        countryId: '',
      },
      workAddress: '',
      officeIds: ['BED'],
      negotiatorIds: ['MBW'],
      metadata: {},
      _eTag: '"E13FBA71A43612AE52F7CBF02C6DA0B6"',
      _links: {
        self: {
          href: '/contacts/BED13001801',
        },
        documents: {
          href: '/documents/?ownerType=contact&ownerId=BED13001801',
        },
        identityChecks: {
          href: '/identityChecks/?contactId=BED13001801',
        },
        offices: {
          href: '/offices/?id=BED',
        },
        negotiators: {
          href: '/negotiators/?id=MBW',
        },
      },
      _embedded: {},
    },
  ],
  pageNumber: 1,
  pageSize: 10,
  pageCount: 6,
  totalCount: 6,
  _links: {
    self: {
      href: '/contacts/?PageNumber=1&PageSize=10&name=Philip',
    },
    first: {
      href: '/contacts/?PageNumber=1&PageSize=10&name=Philip',
    },
  },
}
