export const isMobile = '@media screen and (max-width: 767px)'
export const isTablet = '@media screen and (min-width: 768px)'
export const isDesktop = '@media screen and (min-width: 1024px)'
export const isWideScreen = '@media screen and (min-width: 1440px)'
export const isSuperWideScreen = '@media screen and (min-width: 1920px)'
export const is4KScreen = '@media screen and (min-width: 2560px)'
