export const white = '#fff'
export const black = '#12263f'
export const greyDark = '#6e84a3'
export const grey = '#95aac9'
export const greyLighter = '#e3ebf6'
export const greyLightest = '#f9fbfd'
export const green = '#5fe781'
export const greenLighter = '#acf2bd'
export const greenLightest = '#e6ffed'
export const red = '#e96171'
export const redLighter = '#fdb8c0'
export const redLightest = '#ffeef0'

export const reapitDarkBlue = '#262f69'
export const reapitMidBlue = '#0061a8'
export const reapitLightBlue = '#23a4de'
export const reapitLightestBlue = '#7bc9eb'

export const reapitOrange = '#ec631b'
export const reapitLime = '#cddb00'
export const reapitTeal = '#006580'
export const reapitPlumb = '#7a2c81'
export const reapitPurple = '#a4185c'
export const reapitGold = '#ffb71b'
export const reapitGreen = '#a0c862'
export const reapitRed = '#d3033d'
