addReviewers: true
addAssignees: author
numberOfReviewers: 2
numberOfAssignees: 1
useReviewGroups: true
reviewGroups:
  primaryReviewer:
    - vuhuucuong
    - phmngocnghia
    - trankhacvy
    - nphivu414
    - ant066
  secondaryReviewer:
    - willmcvay
    - tanphamhaiduong
useAssigneeGroups: false
