export const forSmallMobileOnly = '@media (max-width: 414px)'
export const forMobileOnly = '@media (max-width: 768px)'
export const forMobileAndAbove = '@media (min-width: 768px)'
export const forTabletAndAbove = '@media (min-width: 1024px)'
export const forDesktopAndAbove = '@media (min-width: 1440px)'
export const forWidescreenAndAbove = '@media (min-width: 1800px)'
export const forSuperWidescreenAndAbove = '@media (min-width: 2200px)'
