import { AppDetailModel, AppSummaryModelPagedResult } from '@reapit/foundations-ts-definitions'

export const mockAppsList: AppSummaryModelPagedResult = {
  data: [
    {
      id: '8858e1d0-0539-4079-b4d1-0b7f4a6c8ccc',
      externalId: '1qlgfmrm2eu6750e7ajulu2mc2',
      created: '2021-05-14T14:24:34',
      developerId: '45db5da6-961b-4962-84f6-1159f00d5a91',
      name: 'Test App Dev',
      summary: '',
      developer: 'DFG',
      homePage: '',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: true,
      isFree: false,
      desktopIntegrationTypeIds: [],
      authFlow: 'client_credentials',
      launchUri: '',
      pendingRevisions: true,
      isHidden: false,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/8858e1d0-0539-4079-b4d1-0b7f4a6c8ccc',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/45db5da6-961b-4962-84f6-1159f00d5a91',
          action: 'GET',
        },
      ],
    },
    {
      id: 'f83e679e-a7cd-4889-a7f9-f4a8a8ed5a09',
      externalId: '6smkano1divf74s7pu35tj630o',
      created: '2021-03-04T09:37:00',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Reapit Insights',
      summary: 'Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah.',
      developer: 'Reapit Ltd',
      homePage: 'https://insights.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: false,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Insights-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Insights-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      authFlow: 'code',
      launchUri: 'https://insights.dev.paas.reapit.cloud',
      pendingRevisions: false,
      isHidden: false,
      limitToClientIds: ['RES', 'SBOX', 'XTM'],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/f83e679e-a7cd-4889-a7f9-f4a8a8ed5a09',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: '131efbac-49f5-41d8-98b9-be33b0a4e908',
      externalId: '16k6g95lql59ptchoseqdm5hdi',
      created: '2020-12-21T08:09:42',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Marketplace Management',
      summary: 'Description Description Description Description Description Description Description Description',
      developer: 'Reapit Ltd',
      homePage: 'https://holly.com',
      isListed: true,
      isSandbox: false,
      isFeatured: true,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Connect-Management-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Connect-Management-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      authFlow: 'code',
      launchUri: 'https://marketplace-management.dev.paas.reapit.cloud/offices',
      pendingRevisions: false,
      isHidden: false,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/131efbac-49f5-41d8-98b9-be33b0a4e908',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'ad1689bd-4dc0-4e7c-8b64-487a7541970d',
      externalId: '33cudmt5iu1fimuqddopdfrjdl',
      created: '2020-11-06T08:59:48',
      developerId: '63105eb5-6d51-4345-9e7e-967952a3f1f8',
      name: 'Holly Test App',
      summary:
        'https://holly.com https://holly.com https://holly.com https://holly.comhttps://holly.com https://holly.comhttps://holly.com https://holly.com',
      developer: 'Holly Phillips Testing',
      homePage: 'https://homepage.com',
      isListed: true,
      isSandbox: false,
      isFeatured: true,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Holly-Test-App-icon(1).png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Holly-Test-App-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['PrpMarketing', 'PrintWizard'],
      authFlow: 'code',
      launchUri: 'https://launch.com',
      pendingRevisions: false,
      isHidden: true,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/ad1689bd-4dc0-4e7c-8b64-487a7541970d',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/63105eb5-6d51-4345-9e7e-967952a3f1f8',
          action: 'GET',
        },
      ],
    },
    {
      id: '795fc578-8232-4dbd-a5ff-1240135c0a52',
      externalId: '7dim9s02ifbq623k4d0vk91tgl',
      created: '2020-11-05T08:59:14',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Reapit Payments Portal',
      summary: 'It takes your money and sends it to Sage Pay. Then it updates RPS.',
      developer: 'Reapit Ltd',
      homePage: 'https://reapit.com',
      isListed: true,
      isSandbox: false,
      isFeatured: true,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Payments-Portal-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Payments-Portal-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['Payment'],
      installedOn: '2021-04-20T08:41:47',
      authFlow: 'code',
      launchUri: 'https://payments.dev.paas.reapit.cloud',
      pendingRevisions: false,
      isHidden: false,
      limitToClientIds: ['SBOX', 'RES'],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/795fc578-8232-4dbd-a5ff-1240135c0a52',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: '06ae7f8e-7a01-4b29-9049-1fd86e3ec52b',
      externalId: '5dk5afvtj04tmdlmt4i3aipjk0',
      created: '2020-11-05T08:56:39',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Data Warehouse',
      summary: 'The data warehouse houses lots of data. The data warehouse houses lots of data.',
      developer: 'Reapit Ltd',
      homePage: 'https://data-warehouse-app.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: false,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Data-Warehouse-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Data-Warehouse-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      installedOn: '2021-02-09T16:55:48',
      authFlow: 'code',
      launchUri: 'https://data-warehouse-app.dev.paas.reapit.cloud/login',
      pendingRevisions: false,
      isHidden: true,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/06ae7f8e-7a01-4b29-9049-1fd86e3ec52b',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'a2b9c6f6-0e53-4fcf-a095-be8cc18482b3',
      externalId: '4m6mr1t2d0si3pfl4rludmqei1',
      created: '2020-11-05T08:48:44',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Reapit Connect',
      summary:
        'Reapit Connect removes the overhead of having to build and maintain a user credential directory for your app.',
      developer: 'Reapit Ltd',
      homePage: 'https://reapit-connect.dev.paas.reapit.cloud/welcome',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: true,
      isFree: false,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Connect-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Connect-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      authFlow: 'code',
      launchUri: 'https://reapit-connect.dev.paas.reapit.cloud/welcome',
      pendingRevisions: false,
      isHidden: true,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/a2b9c6f6-0e53-4fcf-a095-be8cc18482b3',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'dab46391-b07d-4869-8614-139aa798cc1f',
      externalId: '7gvr744qtpqn2batr1hc8hie0c',
      created: '2020-11-04T17:11:40',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Online Check List',
      summary:
        'Helps you to get organised, simplify your workflow, and to ensure checks are carried out. Manage your checks online from anywhere.',
      developer: 'Reapit Ltd',
      homePage: 'https://aml-app.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: true,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Online-Check-List-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Online-Check-List-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['Property', 'IdCheck'],
      installedOn: '2021-06-16T10:34:12',
      authFlow: 'code',
      launchUri: 'https://aml-app.dev.paas.reapit.cloud',
      pendingRevisions: true,
      isHidden: false,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/dab46391-b07d-4869-8614-139aa798cc1f',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
    {
      id: 'cfbe6f29-4003-4648-aa5a-8eb777bd606e',
      externalId: '4kr750gbarufkanl2ceasofmpk',
      created: '2020-11-04T17:02:47',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Geo Diary',
      summary: 'GEO Diary is the App for the Negotiator on the go, instant access to your daily & weekly appointments.',
      developer: 'Reapit Ltd',
      homePage: 'https://geo-diary-app.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: true,
      isDirectApi: false,
      isFree: true,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-screen1ImageUrl.png',
      desktopIntegrationTypeIds: ['Applicant', 'Property'],
      authFlow: 'code',
      launchUri: 'https://geo-diary-app.dev.paas.reapit.cloud',
      pendingRevisions: true,
      isHidden: false,
      limitToClientIds: [],
      links: [
        {
          rel: 'self',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/cfbe6f29-4003-4648-aa5a-8eb777bd606e',
          action: 'GET',
        },
        {
          rel: 'developer',
          href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
          action: 'GET',
        },
      ],
    },
  ],
  pageNumber: 1,
  pageSize: 12,
  pageCount: 9,
  totalCount: 9,
}

export const mockAppDetail: AppDetailModel = {
  id: 'cfbe6f29-4003-4648-aa5a-8eb777bd606e',
  created: '2020-11-04T17:02:47',
  developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
  externalId: '4kr750gbarufkanl2ceasofmpk',
  name: 'Geo Diary',
  summary: 'GEO Diary is the App for the Negotiator on the go, instant access to your daily & weekly appointments.',
  description:
    'GEO Diary offers any Negotiator easy and efficient access to your daily and weekly appointments. Either to check the journey to your first appointment from within Agency Cloud or if you are out and about, you can simply view your days appointments from your phone. \r<div>\r</div><div>With one click, you have full visibility of all your viewings, appointments, and inspections. Not only does GEO Diary show you the appointments you have in Agency Cloud, it will also give you journey times based on your current location. \r</div><div>•\tAll your appointments in one place\r</div><div>•\tAccessed through Agency Cloud, Mobile or Tablet\r</div><div>•\tEasy to install and run\r</div><div>•\tETA feature to notify your next appointment with calculated time of arrival\r</div><div>•\tCancel appointment feature\r</div><div>•\tUses your native map application (Google Map or Apple Maps)\r</div><div><br></div>',
  developer: 'Reapit Ltd',
  developerAbout: 'Reapit are an award winning, market leading CRM provider to the property industry',
  supportEmail: 'foundationssupport@reapit.com',
  telephone: '07939549275',
  homePage: 'https://geo-diary-app.dev.paas.reapit.cloud',
  launchUri: 'https://geo-diary-app.dev.paas.reapit.cloud',
  redirectUris: ['http://localhost:8080', 'https://geo-diary-app.dev.paas.reapit.cloud'],
  signoutUris: ['http://localhost:8080/login', 'https://geo-diary-app.dev.paas.reapit.cloud/login'],
  limitToClientIds: [],
  desktopIntegrationTypeIds: ['Applicant', 'Property'],
  authFlow: 'authorisationCode',
  isListed: true,
  isDirectApi: false,
  isSandbox: false,
  isFeatured: true,
  isWebComponent: false,
  pendingRevisions: true,
  termsAndConditionsUrl: 'https://reapit.com',
  privacyPolicyUrl: 'https://reapit.com',
  isFree: true,
  isHidden: false,
  category: {
    id: '9',
    name: 'Tools',
    description: 'General purpose tools',
  },
  scopes: [
    {
      name: 'agencyCloud/applicants.read',
      description: 'Read applicants',
    },
    {
      name: 'agencyCloud/appointments.read',
      description: 'Read appointments',
    },
    {
      name: 'agencyCloud/appointments.write',
      description: 'Write appointments',
    },
    {
      name: 'agencyCloud/contacts.read',
      description: 'Read contacts',
    },
    {
      name: 'agencyCloud/landlords.read',
      description: 'Read landlords',
    },
    {
      name: 'agencyCloud/negotiators.read',
      description: 'Read negotiators',
    },
    {
      name: 'agencyCloud/offers.read',
      description: 'Read offers',
    },
    {
      name: 'agencyCloud/offices.read',
      description: 'Read offices',
    },
    {
      name: 'agencyCloud/properties.read',
      description: 'Read properties',
    },
    {
      name: 'agencyCloud/tenancies.read',
      description: 'Read tenancies',
    },
    {
      name: 'agencyCloud/vendors.read',
      description: 'Read vendors',
    },
  ],
  media: [
    {
      id: '899f4a62-7d9d-42b4-b118-3e290ec4a94e',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-icon.png',
      description: 'Application Icon',
      type: 'icon',
      order: 0,
    },
    {
      id: 'fe393b11-14f3-4e52-a4b7-15af74f44a9e',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-screen1ImageUrl.png',
      description: 'Application Image',
      type: 'image',
      order: 0,
    },
    {
      id: '227de55e-c851-47fb-a512-0728759f009f',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-screen2ImageUrl.png',
      description: 'Application Image',
      type: 'image',
      order: 0,
    },
    {
      id: '2ef5efe8-c476-4a42-b0d1-1e88eb130235',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-screen3ImageUrl.png',
      description: 'Application Image',
      type: 'image',
      order: 0,
    },
    {
      id: '9934b652-3e33-4be9-9399-f0fa6cf0e9da',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Geo-Diary-screen4ImageUrl.png',
      description: 'Application Image',
      type: 'image',
      order: 0,
    },
  ],
  links: [
    {
      rel: 'self',
      href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/cfbe6f29-4003-4648-aa5a-8eb777bd606e',
      action: 'GET',
    },
    {
      rel: 'developer',
      href: 'https://platform.dev.paas.reapit.cloud/marketplace/developers/421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      action: 'GET',
    },
    {
      rel: 'revisions',
      href: 'https://platform.dev.paas.reapit.cloud/marketplace/apps/cfbe6f29-4003-4648-aa5a-8eb777bd606e/revisions',
      action: 'GET',
    },
    {
      rel: 'installations',
      href: 'https://platform.dev.paas.reapit.cloud/marketplace/installations?AppIds=cfbe6f29-4003-4648-aa5a-8eb777bd606e',
      action: 'GET',
    },
  ],
}
