import { OfficeModelPagedResult } from '@reapit/foundations-ts-definitions'

export const mockOfficeList: OfficeModelPagedResult = {
  _embedded: [
    {
      id: 'CNO',
      created: '2020-03-16T08:54:08Z',
      modified: '2020-03-16T08:54:08Z',
      name: 'create new office 5',
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'address 5',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B91 2XX',
        countryId: '',
      },
      workPhone: '0987654321',
      email: 'tester@yahoo.com',
      _eTag: '"B2F623DDF4642ED2AEC0F82D975BEAB4"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/CNO',
        },
        negotiators: {
          href: '/negotiators/?officeId=CNO',
        },
      },
      metadata: {},
    },
    {
      id: 'CKR',
      created: '2020-03-10T10:01:43Z',
      modified: '2020-03-10T10:01:43Z',
      name: '8eck1r06k6ti0c3hm6tdml',
      manager: 'Mr John Smith',
      address: {
        buildingName: '',
        buildingNumber: '15',
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        postcode: 'B91 2XX',
        countryId: 'GB',
      },
      workPhone: '01234 567890',
      email: 'example@email.com',
      _eTag: '"DCD8533F0CA625123A32AE8A78D1F8B4"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/CKR',
        },
        negotiators: {
          href: '/negotiators/?officeId=CKR',
        },
      },
      metadata: {},
    },
    {
      id: 'AAN',
      created: '2020-08-14T05:17:16Z',
      modified: '2020-09-07T03:55:07Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"0F41CC41B47688C4E2FC3E5F7AC142A3"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/AAN',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAN',
        },
      },
      metadata: {},
    },
    {
      id: 'AAO',
      created: '2020-08-14T06:14:03Z',
      modified: '2020-09-07T03:55:08Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"D105203C9D009B04E084D684D58B029F"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/AAO',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAO',
        },
      },
      metadata: {},
    },
    {
      id: 'ACE',
      created: '2020-08-14T06:16:21Z',
      modified: '2020-09-07T03:55:07Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"FCAC3DE125DF80F4FB1F4423B844863A"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/ACE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACE',
        },
      },
      metadata: {},
    },
    {
      id: 'AEE',
      created: '2020-08-14T06:20:04Z',
      modified: '2020-09-07T03:55:07Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"6527D4741B1904766B8327BB1B3D7949"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/AEE',
        },
        negotiators: {
          href: '/negotiators/?officeId=AEE',
        },
      },
      metadata: {},
    },
    {
      id: 'ANE',
      created: '2020-08-14T06:22:45Z',
      modified: '2020-09-07T03:55:08Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"4461E174D1D6288964E558E6A63ADBE8"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/ANE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ANE',
        },
      },
      metadata: {},
    },
    {
      id: 'ARE',
      created: '2020-08-14T06:18:16Z',
      modified: '2020-09-07T03:55:08Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"537DEB599EF2C69F17BC5DC757E74A4D"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/ARE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ARE',
        },
      },
      metadata: {},
    },
    {
      id: 'ATE',
      created: '2020-08-14T06:21:25Z',
      modified: '2020-09-07T03:55:07Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"0AC9EA4837E13546F4F7E500181F5C9A"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/ATE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ATE',
        },
      },
      metadata: {},
    },
    {
      id: 'AWE',
      created: '2020-08-14T06:24:48Z',
      modified: '2020-09-07T03:55:05Z',
      name: 'aa Create new one',
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"B331C06D5255AD1D0684CBB11BCE8F43"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/AWE',
        },
        negotiators: {
          href: '/negotiators/?officeId=AWE',
        },
      },
      metadata: {},
    },
    {
      id: 'ACO',
      created: '2020-08-17T02:15:37Z',
      modified: '2020-09-07T08:11:23Z',
      name: 'aa create office',
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987654321',
      email: 'test@gmail.com',
      _eTag: '"3CC6D739AF48643ADD628F0EBFEA1090"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/ACO',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACO',
        },
      },
      metadata: {},
    },
    {
      id: 'AAE',
      created: '2020-08-11T07:10:06Z',
      modified: '2020-08-11T07:10:06Z',
      name: 'AA Test 11',
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: '123 LonDon',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'A91',
        countryId: '',
      },
      workPhone: '3424243234',
      email: 'tester@reapit.com',
      _eTag: '"DB1808A496EC4F6E1F761119AC30E20D"',
      extrasField: {},
      _links: {
        self: {
          href: '/offices/AAE',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAE',
        },
      },
      metadata: {},
    },
  ],
  pageNumber: 1,
  pageSize: 12,
  pageCount: 12,
  totalPageCount: 18,
  totalCount: 205,
  _links: {
    self: {
      href: '/offices/?PageNumber=1&PageSize=12',
    },
    first: {
      href: '/offices/?PageNumber=1&PageSize=12',
    },
    next: {
      href: '/offices/?PageNumber=2&PageSize=12',
    },
    last: {
      href: '/offices/?PageNumber=18&PageSize=12',
    },
  },
}
