import { Marketplace } from '@reapit/foundations-ts-definitions'

export const mockAppDetailModel: Marketplace.AppDetailModel = {
  id: 'f83e679e-a7cd-4889-a7f9-f4a8a8ed5a09',
  created: '2021-03-04T09:37:00',
  developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
  installationId: '',
  publicListedDate: '',
  externalId: '6smkano1divf74s7pu35tj630o',
  name: 'Reapit Insights',
  summary: 'Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah.',
  description:
    'Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah.&nbsp;',
  developer: 'Reapit Ltd Internal',
  developerAbout: 'About us',
  supportEmail: 'support@reapit.com',
  telephone: '077777777',
  homePage: 'https://insights.dev.paas.reapit.cloud',
  launchUri: 'https://insights.dev.paas.reapit.cloud',
  redirectUris: ['http://localhost:8080', 'https://insights.dev.paas.reapit.cloud'],
  signoutUris: ['http://localhost:8080/login', 'https://insights.dev.paas.reapit.cloud/login'],
  limitToClientIds: ['RES', 'SBOX', 'XTM', 'ACR'],
  desktopIntegrationTypeIds: [],
  products: ['agencyCloud'],
  installedOn: '',
  authFlow: 'authorisationCode',
  isListed: false,
  isDirectApi: false,
  isSandbox: false,
  isFeatured: false,
  isWebComponent: false,
  pendingRevisions: true,
  termsAndConditionsUrl: 'https://insights.dev.paas.reapit.cloud',
  privacyPolicyUrl: 'https://insights.dev.paas.reapit.cloud',
  pricingUrl: 'https://insights.dev.paas.reapit.cloud',
  isFree: false,
  isHidden: false,
  categories: [
    {
      id: '6',
      name: 'Communication',
      description: 'Messaging and communication',
    },
  ],
  scopes: [
    {
      name: 'agencyCloud/applicants.write',
      description: 'Write applicants',
    },
  ],
  media: [
    {
      id: '1768ac4f-043b-4d52-8e13-262c63107c5d',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Insights-icon.png',
      description: 'Application Icon',
      type: 'icon',
      order: 0,
    },
    {
      id: 'f230d1e2-2468-40a7-aa3f-ccf656c59ddb',
      uri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Insights-screen1ImageUrl.png',
      description: 'Application Image',
      type: 'image',
      order: 0,
    },
  ],
}

export const mockAppSummaryModelPagedResult: Marketplace.AppSummaryModelPagedResult = {
  data: [
    {
      id: 'f83e679e-a7cd-4889-a7f9-f4a8a8ed5a09',
      publicListedDate: '',
      externalId: '6smkano1divf74s7pu35tj630o',
      created: '2021-03-04T09:37:00',
      developerId: '421b65bc-dd09-4c34-90fa-dacc3cd2ff5a',
      name: 'Reapit Insights',
      summary: 'Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah. Blah blah blah.',
      developer: 'Reapit Ltd Internal',
      homePage: 'https://insights.dev.paas.reapit.cloud',
      isListed: true,
      isSandbox: false,
      isFeatured: false,
      isDirectApi: false,
      isFree: false,
      iconUri: 'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Insights-icon.png',
      featuredImageUri:
        'https://reapit-marketplace-app-media-dev.s3.eu-west-2.amazonaws.com/Reapit-Insights-screen1ImageUrl.png',
      desktopIntegrationTypeIds: [],
      products: ['agencyCloud'],
      installedOn: '',
      authFlow: 'code',
      launchUri: 'https://insights.dev.paas.reapit.cloud',
      pendingRevisions: false,
      isHidden: false,
      limitToClientIds: ['RES', 'SBOX', 'XTM', 'ACR'],
    },
  ],
  pageNumber: 1,
  pageSize: 12,
  pageCount: 1,
  totalCount: 1,
}
