import { Marketplace } from '@reapit/foundations-ts-definitions'

export const mockDeveloperModelPagedResult: Marketplace.DeveloperModelPagedResult = {
  data: [
    {
      id: '8240d435-9e6f-4271-a863-7774d199461a',
      created: '2022-03-03T10:18:04',
      modified: '2022-04-29T11:07:45',
      externalId: '',
      name: 'Sales Team',
      company: 'Reapit Sales',
      jobTitle: '',
      email: 'test@example.com',
      telephone: '',
      agreedTerms: '',
      isInactive: false,
      about: '',
      website: 'https://www.reapit.com',
      taxNumber: 'VAT Number',
      registrationNumber: 'Company Reg Number',
      billingEmail: 'test@example.com',
      billingTelephone: '01211112222',
      billingKeyContact: '',
      reapitReference: 'FoOOOO',
      noTaxRegistration: false,
      nationalInsurance: '',
      status: 'confirmed',
      notificationsEmail: '',
      maxAppsUnlisted: 10,
      developerEditionSubscriptionCost: 0,
      companyAddress: {
        buildingName: 'Radcliffe House',
        buildingNumber: '5',
        line1: 'Blenheim Court',
        line2: 'Solihull',
        line3: '',
        line4: 'solihull',
        postcode: 'B91 2AA',
        countryId: 'GB',
      },
    },
  ],
  pageNumber: 1,
  pageSize: 12,
  pageCount: 1,
  totalCount: 1,
}
