import Routes from './routes'

export const ELEMENTS_V3_PAGES = [
  Routes.DESKTOP,
  Routes.ELEMENTS,
  Routes.GRAPHQL,
  Routes.SWAGGER,
  Routes.API_DOCS,
  Routes.ANALYTICS_SCHEMA_DOCS,
  Routes.WEBHOOKS_ABOUT,
  Routes.WEBHOOKS_LOGS,
  Routes.WEBHOOKS_MANAGE,
  Routes.WEBHOOKS_NEW,
  Routes.APPS_NEW,
  Routes.CUSTOMER_REGISTER,
  Routes.ANALYTICS,
  Routes.ANALYTICS_COSTS,
  Routes.ANALYTICS_API_CALLS,
  Routes.ANALYTICS_INSTALLATIONS,
  Routes.ANALYTICS_COST_CALCULATOR,
  Routes.IAAS,
]
