const Routes = {
  AUTHENTICATION: '/authentication',
  AUTHENTICATION_LOGIN_TYPE: '/authentication/:loginType',
  DEVELOPER: '/developer',
  DEVELOPER_WELCOME: '/developer/welcome',
  APPS: '/developer/apps',
  DEVELOPER_APP_DETAIL: '/developer/apps/:appid',
  DEVELOPER_SWAGGER: '/developer/swagger',
  DEVELOPER_DESKTOP: '/developer/desktop',
  APPS_EDIT: '/developer/apps/:appid/edit',
  DEVELOPER_API_DOCS: '/developer/api-docs',
  ANALYTICS: '/developer/analytics',
  ANALYTICS_TAB: '/developer/analytics/:activeTab?',
  DEVELOPER_RESET_PASSWORD: '/developer/reset-password',
  DEVELOPER_WEBHOOKS: '/developer/webhooks',
  SETTINGS: '/developer/settings/',
  SETTINGS_ORGANISATION_TAB: '/developer/settings/organisation',
  SETTINGS_BILLING_TAB: '/developer/settings/billing',
  SUBMIT_APP: '/developer/submit-app',
  DEVELOPER_HELP: '/developer/help',
  DEVELOPER_APP_PREVIEW: '/developer/apps/:appId/preview',
  DEVELOPER_EDITION_DOWNLOAD: '/developer/edition-download',
  REGISTER: '/register',
  REGISTER_CONFIRM: '/register/confirm',
  LOGIN: '/developer/login',
  FOUR_O_FOUR: '/404',
  FORGOT_PASSWORD: '/developer/forgot-password',
}

export default Routes
