# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'

jobs:
- job: buildWebApp
  displayName: Test and build web app
  pool:
    vmImage: 'ubuntu-latest'
  # variables:
  # - group: 
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: yarn install
    displayName: Install deps
    failOnStderr: true

  # - bash: printenv > src/constants/.env
  #   displayName: Injects ENVs
  #   env:

  - script: yarn test:ci
    displayName: Unit tests
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  - script: yarn build
    displayName: Build static assets
    failOnStderr: true

