/**
 * TODO: will refactor this to separate DEVELOPER PORTAL ACTIONS, CLIENT AND ADMIN
 * by <<PORTAL_NAME>>_<<ACTION NAME>>
 * Please follow the <<STATE>>_<<ACTION_TYPE>> pattern and group actions by STATE
 */
const ActionTypes = {
  // Auth actions
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_CHANGE_LOGIN_TYPE: 'AUTH_CHANGE_LOGIN_TYPE',
  AUTH_SET_REFRESH_SESSION: 'AUTH_SET_REFRESH_SESSION',
  AUTH_CLEAR: 'AUTH_CLEAR',
  USER_ACCEPT_TERM_AND_CONDITION: 'USER_ACCEPT_TERM_AND_CONDITION',

  SET_INIT_CLIENT_TERMS_ACCEPTED_STATE_FROM_COOKIE: 'SET_INIT_CLIENT_TERMS_ACCEPTED_STATE_FROM_COOKIE',
  SET_CLIENT_TERM_ACCEPTED_COOKIE_AND_STATE: 'SET_CLIENT_TERM_ACCEPTED_COOKIE_AND_STATE',

  SET_TERMS_ACCEPTED_STATE: 'SET_TERMS_ACCEPTED_STATE',

  // Error actions
  ERROR_THROWN_COMPONENT: 'ERROR_THROWN_COMPONENT',
  ERROR_THROWN_SERVER: 'ERROR_THROWN_SERVER',
  ERROR_CLEARED_COMPONENT: 'ERROR_CLEARED_COMPONENT',
  ERROR_CLEARED_SERVER: 'ERROR_CLEARED_SERVER',

  // notificarion message actions
  SHOW_NOTIFICATION_MESSAGE: 'SHOW_NOTIFICATION_MESSAGE',
  HIDE_NOTIFICATION_MESSAGE: 'HIDE_NOTIFICATION_MESSAGE',

  // Client actions
  CLIENT_FETCH_APP_SUMMARY: 'CLIENT_FETCH_APP_SUMMARY',
  CLIENT_FETCH_APP_SUMMARY_SUCCESS: 'CLIENT_FETCH_APP_SUMMARY_SUCCESS',
  CLIENT_FETCH_APP_SUMMARY_FAILED: 'CLIENT_FETCH_APP_SUMMARY_FAILED',
  CLIENT_CLEAR_APP_SUMMARY: 'CLIENT_CLEAR_APP_SUMMARY',

  // Client App Detail
  CLIENT_FETCH_APP_DETAIL: 'CLIENT_FETCH_APP_DETAIL',
  CLIENT_FETCH_APP_DETAIL_FAILED: 'CLIENT_FETCH_APP_DETAIL_FAILED',
  CLIENT_FETCH_APP_DETAIL_SUCCESS: 'CLIENT_FETCH_APP_DETAIL_SUCCESS',

  // Client Web Component Config
  CLIENT_FETCH_WEB_COMPONENT_CONFIG: 'CLIENT_FETCH_WEB_COMPONENT_CONFIG',
  CLIENT_FETCH_WEB_COMPONENT_CONFIG_SUCCESS: 'CLIENT_FETCH_WEB_COMPONENT_CONFIG_SUCCESS',
  CLIENT_UPDATE_WEB_COMPONENT_CONFIG: 'CLIENT_UPDATE_WEB_COMPONENT_CONFIG',
  CLIENT_UPDATE_WEB_COMPONENT_CONFIG_FAILED: 'CLIENT_UPDATE_WEB_COMPONENT_CONFIG_FAILED',
  CLIENT_FETCH_WEB_COMPONENT_CONFIG_FAILED: 'CLIENT_FETCH_WEB_COMPONENT_CONFIG_FAILED',
  //
  CLIENT_FETCH_NEGOTIATORS_SUCCESS: 'CLIENT_FETCH_NEGOTIATORS_SUCCESS',

  // Installed apps actions
  INSTALLED_APPS_REQUEST_DATA: 'INSTALLED_APPS_REQUEST_DATA',
  INSTALLED_APPS_LOADING: 'INSTALLED_APPS_LOADING',
  INSTALLED_APPS_REQUEST_DATA_FAILURE: 'INSTALLED_APPS_REQUEST_DATA_FAILURE',
  INSTALLED_APPS_RECEIVE_DATA: 'INSTALLED_APPS_RECEIVE_DATA',
  INSTALLED_APPS_CLEAR_DATA: 'INSTALLED_APPS_CLEAR_DATA',

  // My apps actions
  MY_APPS_REQUEST_DATA: 'MY_APPS_REQUEST_DATA',
  MY_APPS_LOADING: 'MY_APPS_LOADING',
  MY_APPS_REQUEST_DATA_FAILURE: 'MY_APPS_REQUEST_DATA_FAILURE',
  MY_APPS_RECEIVE_DATA: 'MY_APPS_RECEIVE_DATA',
  MY_APPS_CLEAR_DATA: 'MY_APPS_CLEAR_DATA',

  // App Detail actions
  APP_DETAIL_REQUEST_DATA: 'APP_DETAIL_REQUEST_DATA',
  APP_DETAIL_LOADING: 'APP_DETAIL_LOADING',
  APP_DETAIL_REQUEST_DATA_FAILURE: 'APP_DETAIL_REQUEST_DATA_FAILURE',
  APP_DETAIL_RECEIVE_DATA: 'APP_DETAIL_RECEIVE_DATA',
  APP_DETAIL_CLEAR_DATA: 'APP_DETAIL_CLEAR_DATA',
  APP_DETAIL_IS_STALE: 'APP_DETAIL_IS_STALE',

  REQUEST_AUTHENTICATION_CODE: 'REQUEST_AUTHENTICATION_CODE',
  REQUEST_AUTHENTICATION_CODE_SUCCESS: 'REQUEST_AUTHENTICATION_CODE_SUCCESS',
  REQUEST_AUTHENTICATION_CODE_FAILURE: 'REQUEST_AUTHENTICATION_CODE_FAILURE',
  REMOVE_AUTHENTICATION_CODE: 'REMOVE_AUTHENTICATION_CODE',

  // categories
  CATEGORIES_RECEIVE_DATA: 'CATEGORIES_RECEIVE_DATA',

  // Installations
  APP_INSTALLATIONS_REQUEST_DATA: 'APP_INSTALLATIONS_REQUEST_DATA',
  APP_INSTALLATIONS_RECEIVE_DATA: 'APP_INSTALLATIONS_RECEIVE_DATA',
  APP_INSTALLATIONS_REQUEST_DATA_FAILURE: 'APP_INSTALLATIONS_REQUEST_DATA_FAILURE',
  APP_INSTALLATIONS_FILTER_REQUEST_DATA: 'APP_INSTALLATIONS_FILTER_REQUEST_DATA',
  APP_INSTALLATIONS_FILTER_RECEIVE_DATA: 'APP_INSTALLATIONS_FILTER_RECEIVE_DATA',
  APP_INSTALLATIONS_FILTER_REQUEST_DATA_FAILURE: 'APP_INSTALLATIONS_FILTER_REQUEST_DATA_FAILURE',

  APP_INSTALLATIONS_REQUEST_INSTALL: 'APP_INSTALLATIONS_REQUEST_INSTALL',
  APP_INSTALLATIONS_REQUEST_UNINSTALL: 'APP_INSTALLATIONS_REQUEST_UNINSTALL',
  APP_INSTALLATIONS_SET_FORM_STATE: 'APP_INSTALLATIONS_SET_FORM_STATE',

  // integration types
  FETCH_DESKTOP_INTEGRATION_TYPES: 'FETCH_DESKTOP_INTEGRATION_TYPES',
  FETCH_DESKTOP_INTEGRATION_TYPES_SUCCESS: 'FETCH_DESKTOP_INTEGRATION_TYPES_SUCCESS',
  FETCH_DESKTOP_INTEGRATION_TYPES_FAILURE: 'FETCH_DESKTOP_INTEGRATION_TYPES_FAILURE',
}

export default ActionTypes
