const Routes = {
  CLIENT: '/client/apps',
  INSTALLED_APPS: '/client/installed',
  INSTALLED_APPS_PAGINATE: '/client/installed/:page',
  MY_APPS: '/client/manage',
  MY_APPS_PAGINATE: '/client/manage/:page',
  DEVELOPER: '/developer',
  DEVELOPER_WELCOME: '/developer/welcome',
  DEVELOPER_MY_APPS: '/developer/apps',
  DEVELOPER_SWAGGER: '/developer/swagger',
  DEVELOPER_ELEMENTS: '/developer/elements',
  DEVELOPER_MY_APPS_PAGINATE: '/developer/apps/:page',
  DEVELOPER_MY_APPS_EDIT: '/developer/apps/:appid/edit',
  DEVELOPER_API_DOCS: '/developer/api-docs',
  DEVELOPER_ANALYTICS: '/developer/analytics',
  DEVELOPER_ANALYTICS_PAGINATE: '/developer/analytics/:page',
  DEVELOPER_RESET_PASSWORD: '/developer/reset-password',
  SETTINGS: '/developer/settings',
  SUBMIT_APP: '/developer/submit-app',
  DEVELOPER_HELP: '/developer/help',
  REGISTER: '/register',
  REGISTER_CONFIRM: '/register/confirm',
  ADMIN: '/admin',
  ADMIN_APPS: '/admin/apps',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_APPROVALS_PAGINATE: '/admin/approvals/:page',
  ADMIN_DEV_MANAGEMENT: '/admin/dev-management',
  ADMIN_DEV_MANAGEMENT_PAGINATE: '/admin/dev-management/:page',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_STATS: '/admin/stats',
  CLIENT_LOGIN: '/client/login',
  DEVELOPER_LOGIN: '/developer/login',
  FOUR_O_FOUR: '/404',
  FORGOT_PASSWORD: '/developer/forgot-password',
}

export default Routes
