const Routes = {
  AUTHENTICATION: '/authentication',
  AUTHENTICATION_LOGIN_TYPE: '/authentication/:loginType',
  APPS: '/client/apps',
  APP_DETAIL: '/client/apps/:appid',
  APP_DETAIL_MANAGE: '/client/apps/:appid/manage',
  WELCOME: '/client/welcome',
  INSTALLED_APPS: '/client/installed',
  INSTALLED_APPS_PAGINATE: '/client/installed/:page',
  MY_APPS: '/client/manage',
  MY_APPS_PAGINATE: '/client/manage/:page',
  SETTINGS: '/client/settings',
  HELP: '/client/help',
  LOGIN: '/client/login',
  FOUR_O_FOUR: '/404',

  // Todo: Will remove after remove unused components
  CLIENT: '/client/apps',
  CLIENT_APP_DETAIL: '/client/apps/:appid',
  CLIENT_APP_DETAIL_MANAGE: '/client/apps/:appid/manage',
  CLIENT_WELCOME: '/client/welcome',
  DEVELOPER: '/developer',
  DEVELOPER_WELCOME: '/developer/welcome',
  DEVELOPER_MY_APPS: '/developer/apps',
  DEVELOPER_APP_DETAIL: '/developer/apps/:appid',
  DEVELOPER_SWAGGER: '/developer/swagger',
  DEVELOPER_DESKTOP: '/developer/desktop',
  DEVELOPER_MY_APPS_EDIT: '/developer/apps/:appid/edit',
  DEVELOPER_API_DOCS: '/developer/api-docs',
  DEVELOPER_ANALYTICS: '/developer/analytics',
  DEVELOPER_ANALYTICS_TAB: '/developer/analytics/:activeTab?',
  DEVELOPER_RESET_PASSWORD: '/developer/reset-password',
  DEVELOPER_WEBHOOKS: '/developer/webhooks',
  DEVELOPER_SETTINGS: '/developer/settings/',
  DEVELOPER_SETTINGS_ORGANISATION_TAB: '/developer/settings/organisation',
  DEVELOPER_SETTINGS_BILLING_TAB: '/developer/settings/billing',
  SUBMIT_APP: '/developer/submit-app',
  DEVELOPER_HELP: '/developer/help',
  DEVELOPER_APP_PREVIEW: '/developer/apps/:appId/preview',
  DEVELOPER_EDITION_DOWNLOAD: '/developer/edition-download',
  CLIENT_HELP: '/client/help',
  REGISTER: '/register',
  REGISTER_CONFIRM: '/register/confirm',
  ADMIN: '/admin',
  ADMIN_APPS: '/admin/apps',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_DEV_MANAGEMENT: '/admin/dev-management',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_STATS: '/admin/stats',
  ADMIN_BILLING: '/admin/billing',
  DEVELOPER_LOGIN: '/developer/login',
  FORGOT_PASSWORD: '/developer/forgot-password',
}

export default Routes
