/**
 * TODO: will refactor this to separate DEVELOPER PORTAL ACTIONS, CLIENT AND ADMIN
 * by <<PORTAL_NAME>>_<<ACTION NAME>>
 * Please follow the <<STATE>>_<<ACTION_TYPE>> pattern and group actions by STATE
 */
const ActionTypes = {
  // DEVELOPER PORTAL
  DEVELOPER_FETCH_MY_IDENTITY: 'DEVELOPER_FETCH_MY_IDENTITY',
  DEVELOPER_SET_MY_IDENTITY: 'DEVELOPER_SET_MY_IDENTITY',
  // CLIENT PORTAL

  // ADMIN PORTAL

  // Delete
  APP_DELETE_SET_INIT_FORM_STATE: 'APP_DELETE_SET_INIT_FORM_STATE',
  APP_DELETE_REQUEST: 'APP_DELETE_REQUEST',
  APP_DELETE_REQUEST_LOADING: 'APP_DELETE_REQUEST_LOADING',
  APP_DELETE_REQUEST_SUCCESS: 'APP_DELETE_REQUEST_SUCCESS',
  APP_DELETE_REQUEST_FAILURE: 'APP_DELETE_REQUEST_FAILURE',

  // Auth actions
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_CHANGE_LOGIN_TYPE: 'AUTH_CHANGE_LOGIN_TYPE',
  AUTH_SET_REFRESH_SESSION: 'AUTH_SET_REFRESH_SESSION',
  AUTH_CLEAR: 'AUTH_CLEAR',
  USER_ACCEPT_TERM_AND_CONDITION: 'USER_ACCEPT_TERM_AND_CONDITION',

  SET_INIT_DEVELOPER_TERMS_ACCEPTED_STATE_FROM_COOKIE: 'SET_INIT_DEVELOPER_TERMS_ACCEPTED_STATE_FROM_COOKIE',
  SET_DEVELOPER_TERM_ACCEPTED_COOKIE_AND_STATE: 'SET_DEVELOPER_TERM_ACCEPTED_COOKIE_AND_STATE',

  SET_INIT_CLIENT_TERMS_ACCEPTED_STATE_FROM_COOKIE: 'SET_INIT_CLIENT_TERMS_ACCEPTED_STATE_FROM_COOKIE',
  SET_CLIENT_TERM_ACCEPTED_COOKIE_AND_STATE: 'SET_CLIENT_TERM_ACCEPTED_COOKIE_AND_STATE',

  SET_TERMS_ACCEPTED_STATE: 'SET_TERMS_ACCEPTED_STATE',

  // Error actions
  ERROR_THROWN_COMPONENT: 'ERROR_THROWN_COMPONENT',
  ERROR_THROWN_SERVER: 'ERROR_THROWN_SERVER',
  ERROR_CLEARED_COMPONENT: 'ERROR_CLEARED_COMPONENT',
  ERROR_CLEARED_SERVER: 'ERROR_CLEARED_SERVER',

  // notificarion message actions
  SHOW_NOTIFICATION_MESSAGE: 'SHOW_NOTIFICATION_MESSAGE',
  HIDE_NOTIFICATION_MESSAGE: 'HIDE_NOTIFICATION_MESSAGE',

  // App Detail actions
  APP_DETAIL_REQUEST_DATA: 'APP_DETAIL_REQUEST_DATA',
  APP_DETAIL_LOADING: 'APP_DETAIL_LOADING',
  APP_DETAIL_REQUEST_DATA_FAILURE: 'APP_DETAIL_REQUEST_DATA_FAILURE',
  APP_DETAIL_RECEIVE_DATA: 'APP_DETAIL_RECEIVE_DATA',
  APP_DETAIL_CLEAR_DATA: 'APP_DETAIL_CLEAR_DATA',
  APP_DETAIL_IS_STALE: 'APP_DETAIL_IS_STALE',

  REQUEST_AUTHENTICATION_CODE: 'REQUEST_AUTHENTICATION_CODE',
  REQUEST_AUTHENTICATION_CODE_SUCCESS: 'REQUEST_AUTHENTICATION_CODE_SUCCESS',
  REQUEST_AUTHENTICATION_CODE_FAILURE: 'REQUEST_AUTHENTICATION_CODE_FAILURE',
  REMOVE_AUTHENTICATION_CODE: 'REMOVE_AUTHENTICATION_CODE',

  // Admin Apps actions
  ADMIN_APPS_UPDATE_FILTER: 'ADMIN_APPS_UPDATE_FILTER',
  ADMIN_APPS_REQUEST_DATA: 'ADMIN_APPS_REQUEST_DATA',
  ADMIN_APPS_RECEIVE_DATA: 'ADMIN_APPS_RECEIVE_DATA',
  ADMIN_APPS_REQUEST_FAILURE: 'ADMIN_APPS_REQUEST_FAILURE',
  ADMIN_APPS_REQUEST_FEATURED: 'ADMIN_APPS_REQUEST_FEATURED',
  ADMIN_APPS_SET_FORM_STATE: 'ADMIN_APPS_SET_FORM_STATE',

  // Admin Approvals actions
  APPROVALS_REQUEST_DATA: 'APPROVALS_REQUEST_DATA',
  APPROVALS_REQUEST_FAILURE: 'APPROVALS_REQUEST_FAILURE',
  APPROVALS_LOADING: 'APPROVALS_LOADING',
  APPROVALS_RECEIVE_DATA: 'APPROVALS_RECEIVE_DATA',
  APPROVALS_CLEAR_DATA: 'APPROVALS_CLEAR_DATA',

  // Admin Dev Management
  ADMIN_DEV_MANAGEMENT_REQUEST_DATA: 'ADMIN_DEV_MANAGEMENT_REQUEST_DATA',
  ADMIN_DEV_MANAGEMENT_REQUEST_FAILURE: 'ADMIN_DEV_MANAGEMENT_REQUEST_FAILURE',
  ADMIN_DEV_MANAGEMENT_LOADING: 'ADMIN_DEV_MANAGEMENT_LOADING',
  ADMIN_DEV_MANAGEMENT_RECEIVE_DATA: 'ADMIN_DEV_MANAGEMENT_RECEIVE_DATA',
  ADMIN_DEV_MANAGEMENT_CLEAR_DATA: 'ADMIN_DEV_MANAGEMENT_CLEAR_DATA',

  // Admin Dev Management Delete Developer
  DEVELOPER_SET_STATUS_SET_INIT_FORM_STATE: 'DEVELOPER_SET_STATUS_SET_INIT_FORM_STATE',
  DEVELOPER_SET_STATUS_REQUEST: 'DEVELOPER_SET_STATUS_REQUEST',
  DEVELOPER_SET_STATUS_REQUEST_LOADING: 'DEVELOPER_SET_STATUS_REQUEST_LOADING',
  DEVELOPER_SET_STATUS_REQUEST_SUCCESS: 'DEVELOPER_SET_STATUS_REQUEST_SUCCESS',
  DEVELOPER_SET_STATUS_REQUEST_FAILURE: 'DEVELOPER_SET_STATUS_REQUEST_FAILURE',

  // Revision Detail actions
  REVISION_DETAIL_REQUEST_DATA: 'REVISION_DETAIL_REQUEST_DATA',
  REVISION_DETAIL_LOADING: 'REVISION_DETAIL_LOADING',
  REVISION_DETAIL_REQUEST_DATA__FAILURE: 'REVISION_DETAIL_REQUEST_DATA__FAILURE',
  REVISION_DETAIL_RECEIVE_DATA: 'REVISION_DETAIL_RECEIVE_DATA',
  REVISION_DETAIL_CLEAR_DATA: 'REVISION_DETAIL_CLEAR_DATA',

  REVISION_SUBMIT_APPROVE: 'REVISION_SUBMIT_APPROVE',
  REVISION_APPROVE_SET_FORM_STATE: 'REVISION_APPROVE_SET_FORM_STATE',
  REVISION_SUBMIT_DECLINE: 'REVISION_SUBMIT_DECLINE',
  REVISION_DECLINE_SET_FORM_STATE: 'REVISION_DECLINE_SET_FORM_STATE',

  // Revisions actions
  REVISIONS_REQUEST_DATA: 'REVISIONS_REQUEST_DATA',
  REVISIONS_RECEIVE_DATA: 'REVISIONS_RECEIVE_DATA',
  REVISIONS_REQUEST_DATA_FAILURE: 'REVISIONS_REQUEST_DATA_FAILURE',
  REVISIONS_CLEAR_DATA: 'REVISIONS_CLEAR_DATA',

  // Admin stats
  STATISTICS_REQUEST_DATA: 'STATISTICS_REQUEST_DATA',
  STATISTICS_RECEIVE_DATA: 'STATISTICS_RECEIVE_DATA',
  STATISTICS_REQUEST_DATA_FAILURE: 'STATISTICS_REQUEST_DATA_FAILURE',
}

export default ActionTypes
