/**
 * TODO: will refactor this to separate DEVELOPER PORTAL ACTIONS, CLIENT AND ADMIN
 * by <<PORTAL_NAME>>_<<ACTION NAME>>
 * Please follow the <<STATE>>_<<ACTION_TYPE>> pattern and group actions by STATE
 */

const ActionTypes = {
  // Delete app
  SET_APP_DELETE_INIT_FORM_STATE: 'SET_APP_DELETE_INIT_FORM_STATE',
  DELETE_REQUEST_APP: 'DELETE_REQUEST_APP',
  DELETE_REQUEST_APP_SUCCESS: 'DELETE_REQUEST_APP_SUCCESS',
  DELETE_REQUEST_APP_FAILED: 'DELETE_REQUEST_APP_FAILED',

  // App Detail actions
  FETCH_APP_DETAIL: 'FETCH_APP_DETAIL',
  FETCH_APP_DETAIL_FAILED: 'FETCH_APP_DETAIL_FAILED',
  FETCH_APP_DETAIL_SUCCESS: 'FETCH_APP_DETAIL_SUCCESS',
  APP_DETAIL_CLEAR_DATA: 'APP_DETAIL_CLEAR_DATA',
  APP_DETAIL_IS_STALE: 'APP_DETAIL_IS_STALE',

  // Admin Apps actions
  APPS_UPDATE_FILTER: 'APPS_UPDATE_FILTER',
  FETCH_APP_LIST: 'FETCH_APP_LIST',
  FETCH_APP_LIST_SUCCESS: 'FETCH_APP_LIST_SUCCESS',
  FETCH_APP_LIST_FAILED: 'FETCH_APP_LIST_FAILED',
  REQUEST_MARK_APP_AS_FEATURED: 'REQUEST_MARK_APP_AS_FEATURED',
  APPS_SET_FORM_STATE: 'APPS_SET_FORM_STATE',

  // Admin Approvals actions
  FETCH_APPROVAL_LIST: 'FETCH_APPROVAL_LIST',
  FETCH_APPROVAL_LIST_FAILED: 'FETCH_APPROVAL_LIST_FAILED',
  FETCH_APPROVAL_LIST_SUCCESS: 'FETCH_APPROVAL_LIST_SUCCESS',

  // Admin Dev Management
  FETCH_DEVELOPER_LIST: 'FETCH_DEVELOPER_LIST',
  FETCH_DEVELOPER_LIST_FAILED: 'FETCH_DEVELOPER_LIST_FAILED',
  FETCH_DEVELOPER_LIST_SUCCESS: 'FETCH_DEVELOPER_LIST_SUCCESS',
  DEVS_MANAGEMENT_CLEAR_DATA: 'DEVS_MANAGEMENT_CLEAR_DATA',

  // Admin Dev Management Delete Developer
  INIT_REQUEST_DEVELOPER_STATUS_FORM_STATE: 'INIT_REQUEST_DEVELOPER_STATUS_FORM_STATE',
  SET_DEVELOPER_STATUS_FORM_STATE: 'SET_DEVELOPER_STATUS_FORM_STATE',
  SET_DEVELOPER_STATUS_FORM_STATE_LOADING: 'SET_DEVELOPER_STATUS_FORM_STATE_LOADING',
  SET_DEVELOPER_STATUS_FORM_STATE_SUCCESS: 'SET_DEVELOPER_STATUS_FORM_STATE_SUCCESS',
  SET_DEVELOPER_STATUS_FORM_STATE_FAILED: 'SET_DEVELOPER_STATUS_FORM_STATE_FAILED',

  // Revision Detail actions
  FETCH_REVISION: 'FETCH_REVISION',
  FETCH_REVISION_FAILED: 'FETCH_REVISION_FAILED',
  FETCH_REVISION_SUCCESS: 'FETCH_REVISION_SUCCESS',
  REVISION_DETAIL_CLEAR_DATA: 'REVISION_DETAIL_CLEAR_DATA',

  REQUEST_APPROVE_REVISION: 'REQUEST_APPROVE_REVISION',
  SET_REQUEST_APPROVE_REVISION_FORM_STATE: 'SET_REQUEST_APPROVE_REVISION_FORM_STATE',
  REQUEST_DECLINE_REVISION: 'REQUEST_DECLINE_REVISION',
  SET_REQUEST_DECLINE_REVISION_FORM_STATE: 'SET_REQUEST_DECLINE_REVISION_FORM_STATE',

  // Admin stats
  FETCH_STATISTICS: 'FETCH_STATISTICS',
  FETCH_STATISTICS_SUCCES: 'FETCH_STATISTICS_SUCCES',
  FETCH_STATISTICS_FAILED: 'FETCH_STATISTICS_FAILED',
}

export default ActionTypes
