/**
 * TODO: will refactor this to separate DEVELOPER PORTAL ACTIONS, CLIENT AND ADMIN
 * by <<PORTAL_NAME>>_<<ACTION NAME>>
 * Please follow the <<STATE>>_<<ACTION_TYPE>> pattern and group actions by STATE
 */
const ActionTypes = {
  // Delete app
  SET_APP_DELETE_INIT_FORM_STATE: 'SET_APP_DELETE_INIT_FORM_STATE',
  DELETE_REQUEST_APP: 'DELETE_REQUEST_APP',
  DELETE_REQUEST_APP_LOADING: 'DELETE_REQUEST_APP_LOADING',
  DELETE_REQUEST_APP_SUCCESS: 'DELETE_REQUEST_APP_SUCCESS',

  DELETE_REQUEST_APP_FAILED: 'DELETE_REQUEST_APP_FAILED',

  // Error actions
  /*
   * TODOME(errorActions)
   *dleete
   */

  ERROR_THROWN_COMPONENT: 'ERROR_THROWN_COMPONENT',
  ERROR_THROWN_SERVER: 'ERROR_THROWN_SERVER',
  ERROR_CLEARED_COMPONENT: 'ERROR_CLEARED_COMPONENT',
  ERROR_CLEARED_SERVER: 'ERROR_CLEARED_SERVER',

  /*
   * TODOME(notiActions)
   * delete
   */

  // notificarion message actions
  SHOW_NOTIFICATION_MESSAGE: 'SHOW_NOTIFICATION_MESSAGE',
  HIDE_NOTIFICATION_MESSAGE: 'HIDE_NOTIFICATION_MESSAGE',

  // App Detail actions
  APP_DETAIL_REQUEST_DATA: 'APP_DETAIL_REQUEST_DATA',
  APP_DETAIL_LOADING: 'APP_DETAIL_LOADING',
  APP_DETAIL_REQUEST_DATA_FAILURE: 'APP_DETAIL_REQUEST_DATA_FAILURE',
  APP_DETAIL_RECEIVE_DATA: 'APP_DETAIL_RECEIVE_DATA',
  APP_DETAIL_CLEAR_DATA: 'APP_DETAIL_CLEAR_DATA',
  APP_DETAIL_IS_STALE: 'APP_DETAIL_IS_STALE',

  // Admin Apps actions
  APPS_UPDATE_FILTER: 'APPS_UPDATE_FILTER',
  APPS_REQUEST_DATA: 'APPS_REQUEST_DATA',
  APPS_RECEIVE_DATA: 'APPS_RECEIVE_DATA',
  APPS_REQUEST_FAILURE: 'APPS_REQUEST_FAILURE',
  APPS_REQUEST_FEATURED: 'APPS_REQUEST_FEATURED',
  APPS_SET_FORM_STATE: 'APPS_SET_FORM_STATE',
  /*
   * TODOME(approvalsActions)
   * failure -> failed
   * action + entity
   */

  // Admin Approvals actions
  APPROVALS_REQUEST_DATA: 'APPROVALS_REQUEST_DATA',
  APPROVALS_REQUEST_FAILURE: 'APPROVALS_REQUEST_FAILURE',
  APPROVALS_LOADING: 'APPROVALS_LOADING',
  APPROVALS_RECEIVE_DATA: 'APPROVALS_RECEIVE_DATA',
  APPROVALS_CLEAR_DATA: 'APPROVALS_CLEAR_DATA',

  // Admin Dev Management
  DEVS_MANAGEMENT_REQUEST_DATA: 'DEVS_MANAGEMENT_REQUEST_DATA',
  DEVS_MANAGEMENT_REQUEST_FAILURE: 'DEVS_MANAGEMENT_REQUEST_FAILURE',
  DEVS_MANAGEMENT_LOADING: 'DEVS_MANAGEMENT_LOADING',
  DEVS_MANAGEMENT_RECEIVE_DATA: 'DEVS_MANAGEMENT_RECEIVE_DATA',
  DEVS_MANAGEMENT_CLEAR_DATA: 'DEVS_MANAGEMENT_CLEAR_DATA',

  /*
   * TODOME(developerStatusActions)
   * aciont + entity
   * failure - failed
   */
  // Admin Dev Management Delete Developer
  DEVELOPER_SET_STATUS_SET_INIT_FORM_STATE: 'DEVELOPER_SET_STATUS_SET_INIT_FORM_STATE',
  DEVELOPER_SET_STATUS_REQUEST: 'DEVELOPER_SET_STATUS_REQUEST',
  DEVELOPER_SET_STATUS_REQUEST_LOADING: 'DEVELOPER_SET_STATUS_REQUEST_LOADING',
  DEVELOPER_SET_STATUS_REQUEST_SUCCESS: 'DEVELOPER_SET_STATUS_REQUEST_SUCCESS',
  DEVELOPER_SET_STATUS_REQUEST_FAILURE: 'DEVELOPER_SET_STATUS_REQUEST_FAILURE',

  /* TODOME(appsManagement)
   * failure -> failed
   * action + entity
   */
  // Revision Detail actions
  REVISION_DETAIL_REQUEST_DATA: 'REVISION_DETAIL_REQUEST_DATA',
  REVISION_DETAIL_LOADING: 'REVISION_DETAIL_LOADING',
  REVISION_DETAIL_REQUEST_DATA__FAILURE: 'REVISION_DETAIL_REQUEST_DATA__FAILURE',
  REVISION_DETAIL_RECEIVE_DATA: 'REVISION_DETAIL_RECEIVE_DATA',
  REVISION_DETAIL_CLEAR_DATA: 'REVISION_DETAIL_CLEAR_DATA',

  REVISION_SUBMIT_APPROVE: 'REVISION_SUBMIT_APPROVE',
  REVISION_APPROVE_SET_FORM_STATE: 'REVISION_APPROVE_SET_FORM_STATE',
  REVISION_SUBMIT_DECLINE: 'REVISION_SUBMIT_DECLINE',
  REVISION_DECLINE_SET_FORM_STATE: 'REVISION_DECLINE_SET_FORM_STATE',

  /*
   * TODOME(statistics)
   * swaagger
   * action + entity
   * failure -> failed
   */
  // Admin stats
  STATISTICS_REQUEST_DATA: 'STATISTICS_REQUEST_DATA',
  STATISTICS_RECEIVE_DATA: 'STATISTICS_RECEIVE_DATA',
  STATISTICS_REQUEST_DATA_FAILURE: 'STATISTICS_REQUEST_DATA_FAILURE',
}

export default ActionTypes
