import { PagedResultOfficeModel_ } from '@reapit/foundations-ts-definitions'

export const officesDataStub: PagedResultOfficeModel_ = {
  _embedded: [
    {
      id: 'TFE',
      created: '2020-08-17T02:22:52Z',
      modified: '2020-08-27T06:33:40Z',
      name: 'ztest office',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'london 3',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987654321',
      email: 'tester@gmail.com',
      _eTag: '"BEE65EE9FBDBCD54EF1E6BE5C0722A07"',
      _links: {
        self: {
          href: '/offices/TFE',
        },
        negotiators: {
          href: '/negotiators/?officeId=TFE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'TNE',
      created: '2020-08-17T02:21:30Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'test new office 1',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987654321',
      email: 'test@gmail.com',
      _eTag: '"4FD18DFF4A9F09C74C299023F376383B"',
      _links: {
        self: {
          href: '/offices/TNE',
        },
        negotiators: {
          href: '/negotiators/?officeId=TNE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'TOE',
      created: '2020-08-17T02:17:35Z',
      modified: '2020-08-17T18:08:14Z',
      name: 'test office',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987654321',
      email: 'test@gmail.com',
      _eTag: '"31B0343FEDB812D3074406019F65463B"',
      _links: {
        self: {
          href: '/offices/TOE',
        },
        negotiators: {
          href: '/negotiators/?officeId=TOE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'TAE',
      created: '2020-08-17T02:16:53Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'test create office',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987654321',
      email: 'test@gmail.com',
      _eTag: '"C5AFEEBA238B96E175C891E58751C847"',
      _links: {
        self: {
          href: '/offices/TAE',
        },
        negotiators: {
          href: '/negotiators/?officeId=TAE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ACO',
      created: '2020-08-17T02:15:37Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'aa create office',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987654321',
      email: 'test@gmail.com',
      _eTag: '"5A4B93BF923353EB49220E0BC38A44BC"',
      _links: {
        self: {
          href: '/offices/ACO',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACO',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ATC',
      created: '2020-08-14T09:57:01Z',
      modified: '2020-08-17T18:08:14Z',
      name: 'aTest create',
      manager: null,
      address: {
        buildingName: 'created 14/08',
        buildingNumber: '1020',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"990E5638727FD727C49E366574822C5F"',
      _links: {
        self: {
          href: '/offices/ATC',
        },
        negotiators: {
          href: '/negotiators/?officeId=ATC',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ACD',
      created: '2020-08-14T06:36:31Z',
      modified: '2020-08-17T18:08:13Z',
      name: 'aTest Updated',
      manager: null,
      address: {
        buildingName: 'update 14/08',
        buildingNumber: '999',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"B225A1FCF82D7AAAA98996B6917551B1"',
      _links: {
        self: {
          href: '/offices/ACD',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACD',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ACT',
      created: '2020-08-14T06:35:55Z',
      modified: '2020-08-17T18:08:13Z',
      name: 'aCreated 222',
      manager: null,
      address: {
        buildingName: 'created',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"352D82A7F11C00A667786AD850A4B328"',
      _links: {
        self: {
          href: '/offices/ACT',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACT',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ACA',
      created: '2020-08-14T06:32:18Z',
      modified: '2020-08-17T18:08:14Z',
      name: 'aUpdated 222',
      manager: null,
      address: {
        buildingName: 'updated',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"19FF384333F7AE951321A3A8CEB75255"',
      _links: {
        self: {
          href: '/offices/ACA',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACA',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ACR',
      created: '2020-08-14T06:30:03Z',
      modified: '2020-09-03T05:49:54Z',
      name: 'aCreated 111',
      manager: null,
      address: {
        buildingName: '1 2 created',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"48444B0027CE7C8D8F65A9BF2B6574A8"',
      _links: {
        self: {
          href: '/offices/ACR',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACR',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: [
          {
            id: 'AAAD',
            created: '2020-08-17T03:38:51Z',
            modified: '2020-08-27T09:14:39Z',
            name: 'aaaaaad',
            jobTitle: 'z',
            active: false,
            officeId: 'ACR',
            workPhone: null,
            mobilePhone: '12343123213',
            email: 'adsadsd@gmail.com',
            metadata: null,
            _eTag: '"1D743CB73B7F65C7263A5CA2A2D183C3"',
            _links: {
              self: {
                href: '/negotiators/AAAD',
              },
              office: {
                href: '/offices/ACR',
              },
            },
            _embedded: null,
          },
          {
            id: 'ASDD',
            created: '2020-08-14T09:24:26Z',
            modified: '2020-08-14T09:24:26Z',
            name: 'asdsd',
            jobTitle: null,
            active: false,
            officeId: 'ACR',
            workPhone: null,
            mobilePhone: '2323123232',
            email: 'sss@gmail.com',
            metadata: null,
            _eTag: '"E145C012FA2A966F227210152E8C720D"',
            _links: {
              self: {
                href: '/negotiators/ASDD',
              },
              office: {
                href: '/offices/ACR',
              },
            },
            _embedded: null,
          },
          {
            id: 'SSSS',
            created: '2020-08-17T01:21:33Z',
            modified: '2020-08-17T01:21:33Z',
            name: 'asssss',
            jobTitle: null,
            active: false,
            officeId: 'ACR',
            workPhone: null,
            mobilePhone: '123455678',
            email: 'sss@gmail.com',
            metadata: null,
            _eTag: '"FCC55A10EE97BFDB8451EEA031D0354C"',
            _links: {
              self: {
                href: '/negotiators/SSSS',
              },
              office: {
                href: '/offices/ACR',
              },
            },
            _embedded: null,
          },
        ],
      },
    },
    {
      id: 'CRT',
      created: '2020-08-14T06:28:17Z',
      modified: '2020-08-17T18:08:14Z',
      name: 'aCreated 111',
      manager: null,
      address: {
        buildingName: 'created',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"7E8C5183A12DA6C68574E8346F7161A4"',
      _links: {
        self: {
          href: '/offices/CRT',
        },
        negotiators: {
          href: '/negotiators/?officeId=CRT',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: [
          {
            id: 'ÁDSD',
            created: '2020-08-14T07:33:32Z',
            modified: '2020-08-14T07:33:32Z',
            name: 'ádasd',
            jobTitle: null,
            active: false,
            officeId: 'CRT',
            workPhone: null,
            mobilePhone: '12334567',
            email: 'ádsd@gmail.com',
            metadata: null,
            _eTag: '"247F361F7665F8C220B2BD7EFAF65B70"',
            _links: {
              self: {
                href: '/negotiators/ÁDSD',
              },
              office: {
                href: '/offices/CRT',
              },
            },
            _embedded: null,
          },
          {
            id: 'KEBU',
            created: '2020-08-26T08:51:13Z',
            modified: '2020-08-26T08:51:13Z',
            name: 'Kevin Busby',
            jobTitle: 'Window Cleaner',
            active: true,
            officeId: 'CRT',
            workPhone: '01234 567890',
            mobilePhone: '07890 123456',
            email: 'kbusby@reapit.com',
            metadata: null,
            _eTag: '"CF5B02A276C3187698567E79829BEF83"',
            _links: {
              self: {
                href: '/negotiators/KEBU',
              },
              office: {
                href: '/offices/CRT',
              },
            },
            _embedded: null,
          },
          {
            id: 'MRKE',
            created: '2020-08-26T08:40:55Z',
            modified: '2020-08-26T08:40:55Z',
            name: 'Mr Kev Dale',
            jobTitle: 'Floor Cleaner',
            active: true,
            officeId: 'CRT',
            workPhone: '01234 567890',
            mobilePhone: '07123456789',
            email: 'kbusby@reapit.com',
            metadata: null,
            _eTag: '"C598123129FCAC43712B4B5805FFECBB"',
            _links: {
              self: {
                href: '/negotiators/MRKE',
              },
              office: {
                href: '/offices/CRT',
              },
            },
            _embedded: null,
          },
          {
            id: 'TTTT',
            created: '2020-08-19T13:59:56Z',
            modified: '2020-08-19T13:59:56Z',
            name: 'tttttttt',
            jobTitle: null,
            active: false,
            officeId: 'CRT',
            workPhone: null,
            mobilePhone: '123456789',
            email: 'agent507@ysearea.com',
            metadata: null,
            _eTag: '"FF52D7B289E4E7F11117BD604841D0C1"',
            _links: {
              self: {
                href: '/negotiators/TTTT',
              },
              office: {
                href: '/offices/CRT',
              },
            },
            _embedded: null,
          },
        ],
      },
    },
    {
      id: 'AOE',
      created: '2020-08-14T06:25:50Z',
      modified: '2020-08-17T18:08:14Z',
      name: 'aUpdated 111',
      manager: null,
      address: {
        buildingName: 'updated',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"534B142752E77B7803D8493797FC95DD"',
      _links: {
        self: {
          href: '/offices/AOE',
        },
        negotiators: {
          href: '/negotiators/?officeId=AOE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: [
          {
            id: 'ASDS',
            created: '2020-08-14T08:54:50Z',
            modified: '2020-08-14T08:54:50Z',
            name: 'asdasd',
            jobTitle: null,
            active: false,
            officeId: 'AOE',
            workPhone: null,
            mobilePhone: '12335454',
            email: 'as@mcil.com',
            metadata: null,
            _eTag: '"E0BC686DB0DC68564970FEA1C23F4167"',
            _links: {
              self: {
                href: '/negotiators/ASDS',
              },
              office: {
                href: '/offices/AOE',
              },
            },
            _embedded: null,
          },
        ],
      },
    },
    {
      id: 'AWE',
      created: '2020-08-14T06:24:48Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"AE1CF04FF0116BE0BC5AF70CDCFE6652"',
      _links: {
        self: {
          href: '/offices/AWE',
        },
        negotiators: {
          href: '/negotiators/?officeId=AWE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ANE',
      created: '2020-08-14T06:22:45Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"B077906BC15AFCE167361155FE1BD19A"',
      _links: {
        self: {
          href: '/offices/ANE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ANE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ATE',
      created: '2020-08-14T06:21:25Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"82BAB556D031971E89C3E40F62CBB7D6"',
      _links: {
        self: {
          href: '/offices/ATE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ATE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: [
          {
            id: 'SSDS',
            created: '2020-08-17T01:36:14Z',
            modified: '2020-08-17T01:36:14Z',
            name: 'asasdsd',
            jobTitle: null,
            active: false,
            officeId: 'ATE',
            workPhone: null,
            mobilePhone: '123456789',
            email: 'sdasd@gmail.com',
            metadata: null,
            _eTag: '"0DCF570F9F0E925C271F2C458044B1F0"',
            _links: {
              self: {
                href: '/negotiators/SSDS',
              },
              office: {
                href: '/offices/ATE',
              },
            },
            _embedded: null,
          },
        ],
      },
    },
    {
      id: 'AEE',
      created: '2020-08-14T06:20:04Z',
      modified: '2020-08-17T18:08:17Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"7DCC2B57C4D24CAF09710DAEB79A17CC"',
      _links: {
        self: {
          href: '/offices/AEE',
        },
        negotiators: {
          href: '/negotiators/?officeId=AEE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: [
          {
            id: 'AASD',
            created: '2020-08-17T02:07:53Z',
            modified: '2020-08-19T01:43:56Z',
            name: 'aasdsa',
            jobTitle: null,
            active: true,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '123421334',
            email: 'agent506@usearea.com',
            metadata: null,
            _eTag: '"8789E7CC443628DAB49C4A0F6AC5412A"',
            _links: {
              self: {
                href: '/negotiators/AASD',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'ABCD',
            created: '2020-08-17T01:48:37Z',
            modified: '2020-08-17T01:48:37Z',
            name: 'abcde',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '123456789',
            email: 'abcde@gmail.com',
            metadata: null,
            _eTag: '"0491F5CA66BC6CBCA0659B08F8039E31"',
            _links: {
              self: {
                href: '/negotiators/ABCD',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'ASAS',
            created: '2020-08-17T01:46:24Z',
            modified: '2020-08-17T01:46:24Z',
            name: 'asasasas',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '123456789',
            email: 'sadsds@gmail.com',
            metadata: null,
            _eTag: '"A42FEFB03861EDF032F8B6ED1405D73C"',
            _links: {
              self: {
                href: '/negotiators/ASAS',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'ADAS',
            created: '2020-08-17T01:53:23Z',
            modified: '2020-08-17T01:53:23Z',
            name: 'asdasdas',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '12324431341',
            email: 'sadasda@gmail.com',
            metadata: null,
            _eTag: '"26179085D689DA34AA8DBAF36B272140"',
            _links: {
              self: {
                href: '/negotiators/ADAS',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'SDFF',
            created: '2020-08-17T02:03:08Z',
            modified: '2020-08-17T02:03:08Z',
            name: 'asdfff',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '123456789',
            email: 'asdad@gmail.com',
            metadata: null,
            _eTag: '"3EAD73754F02EEBE9A2109188E967AB9"',
            _links: {
              self: {
                href: '/negotiators/SDFF',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'ASDQ',
            created: '2020-08-17T01:58:59Z',
            modified: '2020-08-17T01:58:59Z',
            name: 'asdsadq',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '12357754213',
            email: 'dsads@gmail.com',
            metadata: null,
            _eTag: '"10656F2871A9BD9656CF2AF8AEB0F330"',
            _links: {
              self: {
                href: '/negotiators/ASDQ',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'ASAA',
            created: '2020-08-17T02:09:01Z',
            modified: '2020-08-17T02:09:01Z',
            name: 'asdsadsa',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '1232121423',
            email: 'asdsad@gmail.com',
            metadata: null,
            _eTag: '"CC141AE0E9C1724A428CEC1DDB7ED4AB"',
            _links: {
              self: {
                href: '/negotiators/ASAA',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'ADDS',
            created: '2020-08-17T02:09:22Z',
            modified: '2020-08-17T02:09:22Z',
            name: 'asdsdssds',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '12342131233',
            email: 'test@gmail.com',
            metadata: null,
            _eTag: '"01396F6B7C957190FB58C8F135DD800F"',
            _links: {
              self: {
                href: '/negotiators/ADDS',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'TSTC',
            created: '2020-08-17T02:00:03Z',
            modified: '2020-08-17T02:00:03Z',
            name: 'testAccount',
            jobTitle: null,
            active: false,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '123456789',
            email: 'testEmail@gmail.com',
            metadata: null,
            _eTag: '"AD083CB36AB703ED1B1297B0FF1BAD1A"',
            _links: {
              self: {
                href: '/negotiators/TSTC',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
          {
            id: 'TSTT',
            created: '2020-08-17T02:01:07Z',
            modified: '2020-08-17T02:01:29Z',
            name: 'testtt',
            jobTitle: null,
            active: true,
            officeId: 'AEE',
            workPhone: null,
            mobilePhone: '0987654321',
            email: 'test@gmail.com',
            metadata: null,
            _eTag: '"CE7FFCF78731D9C0A8C374522C6E7F04"',
            _links: {
              self: {
                href: '/negotiators/TSTT',
              },
              office: {
                href: '/offices/AEE',
              },
            },
            _embedded: null,
          },
        ],
      },
    },
    {
      id: 'ARE',
      created: '2020-08-14T06:18:16Z',
      modified: '2020-08-17T18:08:15Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"CE5885D53232D4D3A534FFABB7C40C5A"',
      _links: {
        self: {
          href: '/offices/ARE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ARE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'ACE',
      created: '2020-08-14T06:16:21Z',
      modified: '2020-08-17T18:08:17Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"532FB4188D084495B7A10BE0CD4FAB90"',
      _links: {
        self: {
          href: '/offices/ACE',
        },
        negotiators: {
          href: '/negotiators/?officeId=ACE',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'AAO',
      created: '2020-08-14T06:14:03Z',
      modified: '2020-08-17T18:08:16Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"C229384F9C7B8B696835DE8B0071B640"',
      _links: {
        self: {
          href: '/offices/AAO',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAO',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'AAW',
      created: '2020-08-14T05:17:45Z',
      modified: '2020-08-17T18:08:16Z',
      name: 'aa TESTupdate',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '1000',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"C533FEE76AC5B09A0305EAEF79456C02"',
      _links: {
        self: {
          href: '/offices/AAW',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAW',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'AAN',
      created: '2020-08-14T05:17:16Z',
      modified: '2020-08-17T18:08:16Z',
      name: 'aa Create new one',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"AF55F1C366D4F36C979BB93A8D9E6444"',
      _links: {
        self: {
          href: '/offices/AAN',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAN',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'AAR',
      created: '2020-08-14T04:58:40Z',
      modified: '2020-08-17T18:08:16Z',
      name: 'aa Update this one',
      manager: null,
      address: {
        buildingName: 'add building name',
        buildingNumber: '20',
        line1: 'TP HCM',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"F5A8072DEDEA445B6369C706744D4D19"',
      _links: {
        self: {
          href: '/offices/AAR',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAR',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
    {
      id: 'AAC',
      created: '2020-08-14T04:57:47Z',
      modified: '2020-08-17T18:08:16Z',
      name: 'aa Test create valid',
      manager: null,
      address: {
        buildingName: '',
        buildingNumber: '20',
        line1: 'london 2',
        line2: '',
        line3: '',
        line4: '',
        postcode: 'B9100',
        countryId: '',
      },
      workPhone: '987666222',
      email: 'tester@reapit.com',
      _eTag: '"056660B1F183EFFE481796BFA0713000"',
      _links: {
        self: {
          href: '/offices/AAC',
        },
        negotiators: {
          href: '/negotiators/?officeId=AAC',
        },
      },
      metadata: {},
      _embedded: {
        negotiators: null,
      },
    },
  ],
  pageNumber: 1,
  pageSize: 25,
  pageCount: 23,
  _links: {
    self: {
      href: '/offices/?PageNumber=1&PageSize=25&address=B9100&embed=negotiators',
    },
    first: {
      href: '/offices/?PageNumber=1&PageSize=25&address=B9100&embed=negotiators',
    },
  },
}
