import dayjs from 'dayjs'
import { CreateAppointmentModel } from '@reapit/foundations-ts-definitions'

export const BASE_HEADERS = {
  'Content-Type': 'application/json',
  'api-version': '2020-01-31',
  'reapit-customer': 'RES',
}

export const APP_CONSTANTS = {
  negCode: 'HJP',
  appointmentsPayloadEvenDays: [
    {
      start: dayjs().add(1, 'day').hour(8).minute(30).second(0).toISOString(),
      end: dayjs().add(1, 'day').hour(9).minute(0).second(0).toISOString(),
      typeId: 'VW',
      description: 'Front gate is broken, use the side entrance',
      propertyId: 'RPT210023',
      organiserId: 'HJP',
      negotiatorIds: ['HJP'],
      officeIds: ['RPT'],
      attendee: {
        id: 'RPT210025',
        type: 'applicant',
      },
      accompanied: true,
      virtual: false,
      negotiatorConfirmed: false,
      attendeeConfirmed: false,
      propertyConfirmed: false,
    },
    {
      start: dayjs().add(1, 'day').hour(9).minute(30).second(0).toISOString(),
      end: dayjs().add(1, 'day').hour(10).minute(0).second(0).toISOString(),
      typeId: 'IA',
      description: '',
      propertyId: 'BCK080145',
      organiserId: 'HJP',
      negotiatorIds: ['HJP'],
      officeIds: ['RPT'],
      attendee: null,
      accompanied: true,
      virtual: false,
      negotiatorConfirmed: false,
      attendeeConfirmed: false,
      propertyConfirmed: false,
    },
    {
      start: dayjs().add(1, 'day').hour(10).minute(30).second(0).toISOString(),
      end: dayjs().add(1, 'day').hour(11).minute(0).second(0).toISOString(),
      typeId: 'VW',
      description: "The vendor has 2 cats, don't leave the door open",
      propertyId: 'RPT210024',
      organiserId: 'HJP',
      negotiatorIds: ['HJP'],
      officeIds: ['RPT'],
      attendee: {
        id: 'RPT210026',
        type: 'applicant',
      },
      accompanied: true,
      virtual: false,
      negotiatorConfirmed: false,
      attendeeConfirmed: false,
      propertyConfirmed: false,
    },
  ] as CreateAppointmentModel[],
  appointmentsPayloadOddDays: [
    {
      start: dayjs().add(1, 'day').hour(14).minute(30).second(0).toISOString(),
      end: dayjs().add(1, 'day').hour(15).minute(0).second(0).toISOString(),
      typeId: 'VW',
      description: 'Communal entry to access the property. Flat is located on the second floor',
      propertyId: 'RPT210025',
      organiserId: 'HJP',
      negotiatorIds: ['HJP'],
      officeIds: ['RPT'],
      attendee: {
        id: 'RPT210027',
        type: 'applicant',
      },
      accompanied: true,
      virtual: false,
      negotiatorConfirmed: false,
      attendeeConfirmed: false,
      propertyConfirmed: false,
    },
    {
      start: dayjs().add(1, 'day').hour(15).minute(30).second(0).toISOString(),
      end: dayjs().add(1, 'day').hour(16).minute(0).second(0).toISOString(),
      typeId: 'PI',
      description: 'Key under the mat - return to office',
      propertyId: 'RPT210028',
      organiserId: 'HJP',
      negotiatorIds: ['HJP'],
      officeIds: ['RPT'],
      attendee: null,
      accompanied: true,
      virtual: false,
      negotiatorConfirmed: false,
      attendeeConfirmed: false,
      propertyConfirmed: false,
    },
    {
      start: dayjs().add(1, 'day').hour(16).minute(30).second(0).toISOString(),
      end: dayjs().add(1, 'day').hour(17).minute(0).second(0).toISOString(),
      typeId: 'VW',
      description: '',
      propertyId: 'BCK150002',
      organiserId: 'HJP',
      negotiatorIds: ['HJP'],
      officeIds: ['RPT'],
      attendee: null,
      accompanied: true,
      virtual: false,
      negotiatorConfirmed: false,
      attendeeConfirmed: false,
      propertyConfirmed: false,
    },
  ] as CreateAppointmentModel[],
}
