service: connect-session-verify-lambda
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  env: ${file(./config.json)}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      noFrozenLockFile: false
    excludeFiles: src/**/*.test.ts
    keepOutputDirectory: true

provider:
  name: aws
  runtime: nodejs12.x
  region: 'eu-west-2'
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: connect-session-verify-lambda.${self:provider.stage}
    blockPublicAccess: false
  environment:
    NODE_ENV: 'production'
    APP_ENV: ${self:custom.env.appEnv}
    AWS_REGION: ${self:custom.env.awsRegion}
    CONNECT_USERPOOL_ID: ${self:custom.env.connectUserPoolId}
  
package:
  individually: true
  include:
    - dist/**
  exclude:
    - package.json
    - node_modules/**
    - error.log
    - info.log
    - jest.config.js
    - serverless.yml
    - src/**
    - tsconfig.json
    - yml-helpers.js

functions:
  connectSessionVerifyHandler:
    handler: src/index.connectSessionVerifyHandler
    events:
      - http:
          method: POST
          path: /
          cors: false
