import { StringMap } from '../types/core'

export const PLATFORM_HEADERS = {
  'Content-Type': 'application/json',
  Authorization: process.env.PLATFORM_API_KEY
} as StringMap

export const COGNITO_HEADERS = {
  'Content-Type': 'application/json'
} as StringMap

export const mockHeader = {
  ...COGNITO_HEADERS,
  Authorization:
    'Bearer eyJraWQiOiJTSGNVVnpHamIyQXFFSW9MSFpEbHVwR0hHUlwvTmlLKzN0dTEybm5JcXZMOD0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI5ZTQxZTlkNC1kMmY1LTRjZmMtOTcwYi0zNjE5Y2JmNGI1MWEiLCJldmVudF9pZCI6ImM5ODc4NTg0LWIxOTEtNGNmMS1iZjRlLWY5ODQyNGIwZGZhNSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1NjgyNzc1MTAsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS13ZXN0LTIuYW1hem9uYXdzLmNvbVwvZXUtd2VzdC0yX0loRUh6U1Q3YiIsImV4cCI6MTU2ODI4MTExMCwiaWF0IjoxNTY4Mjc3NTEwLCJqdGkiOiJkZDgxZmI3ZC1hM2I4LTRlMmYtYTVhOC1iMTBkZjhkNzBkMDYiLCJjbGllbnRfaWQiOiI1dHZnc2sxdTA2YnB1bWJsb2ZiN2s4bGU5ZCIsInVzZXJuYW1lIjoiOWU0MWU5ZDQtZDJmNS00Y2ZjLTk3MGItMzYxOWNiZjRiNTFhIn0.Te6ML0Ym3MbMqmcI-Ijl74Ky8jN-Jn8ceOiliGBWOMg7dVDnVSs3rARXQaXpEpF8M_OSh2hb8ARNGuCk8o_eiaC1uFJi_sd9ziq1mCw9q1PUdp8lJdPHOw-nEK0RGS4TGaijOMo_l6uAPhPzrPXQfgkw4-ZBtYZnCzdHkkXNXEgqiVxgPYEKqByHZtwDWF7KPPoCZ0J7fXWiWihHmoqOR32cq58BuuxeYPeoOc62PupBOhRESkApIn0b_DAHhUa2tLAdvu8NgRtKgiWk2nDc5nogeZmYvpCdq-eCChI2XSb8fMQm3oASdW_Y9FSA1edaXIeX61nALk91PxMqav2lOw'
}

export const REAPIT_API_BASE_URL = 'https://reapit.cloud.tyk.io'

export const URLS = {
  contacts: '/contacts'
}
