const Routes = {
  CLIENT: '/client/apps',
  INSTALLED_APPS: '/client/installed',
  MY_APPS: '/client/manage',
  MY_APPS_PAGINATE: '/client/installed/:page',
  DEVELOPER: '/developer',
  DEVELOPER_MY_APPS: '/developer/apps',
  DEVELOPER_SWAGGER: '/developer/swagger',
  DEVELOPER_ELEMENTS: '/developer/elements',
  DEVELOPER_MY_APPS_PAGINATE: '/developer/apps/:page',
  DEVELOPER_MY_APPS_EDIT: '/developer/apps/:appid/edit',
  DEVELOPER_API_DOCS: '/developer/api-docs',
  DEVELOPER_DESKTOP_DOCS: '/developer/desktop-docs',
  DEVELOPER_WEB_COMPONENTS: '/developer/web-components',
  DEVELOPER_ANALYTICS: '/developer/analytics',
  DEVELOPER_RESET_PASSWORD: '/developer/reset-password',
  SETTINGS: '/developer/settings',
  SUBMIT_APP: '/developer/submit-app',
  REGISTER: '/register',
  ADMIN: '/admin',
  ADMIN_APPS: '/admin/apps',
  ADMIN_APPROVALS: '/admin/approvals',
  ADMIN_APPROVALS_PAGINATE: '/admin/approvals/:page',
  ADMIN_DEV_MANAGEMENT: '/admin/dev-management',
  ADMIN_DEV_MANAGEMENT_PAGINATE: '/admin/dev-management/:page',
  ADMIN_LOGIN: '/admin/login',
  CLIENT_LOGIN: '/client/login',
  DEVELOPER_LOGIN: '/developer/login',
  FOUR_O_FOUR: '/404',
  FORGOT_PASSWORD: '/developer/forgot-password'
}

export default Routes
