export const appointmentListWidthDesktop = '23rem'
export const appointmentTimeContainerHeight = '3.75rem'
export const controlsHeightDesktop = '10.31rem'
export const navControlsHeightMobile = '11.75rem'
export const navHeight = '3.5rem'
export const navAppointmentListWidthDesktop = '28rem'
export const mapPanelHeight = '5rem'
export const controlsContainerMobileHasMapPanel = '10.5rem'
