version: '3'

services:

  elastic:
    image: softwaremill/elasticmq
    ports:
      - 9324:9324
      - 9325:9325

  app:
    build:
      dockerfile: $PWD/Dockerfile
      context: ../../
    ports:
      - 3000:3000
    env_file:
      .env
    links:
      - elastic
  db:
    platform: linux/x86_64
    image: mysql:5.7
    env_file:
      .env
    ports:
      - 3306:3306
