import { Marketplace } from '@reapit/foundations-ts-definitions'

export const mockDeveloperModel: Marketplace.DeveloperModel = {
  id: 'MOCK_ID',
  created: '2020-11-03T12:18:40',
  modified: '2022-04-08T13:10:39',
  externalId: '',
  name: 'MOCK_NAME',
  company: 'MOCK_COMPANY',
  jobTitle: '',
  email: 'email@mail.com',
  telephone: '077777777',
  agreedTerms: '2020-11-03T12:18:40',
  isInactive: false,
  about: 'All about us',
  website: 'https://example.com',
  taxNumber: 'VAT Number',
  registrationNumber: 'REG NUMBER',
  billingEmail: 'email@example.com',
  billingTelephone: '0777777777',
  billingKeyContact: 'Product Team',
  reapitReference: 'MOCK_REF',
  noTaxRegistration: false,
  nationalInsurance: '',
  status: 'confirmed',
  notificationsEmail: 'email@example.com',
  companyAddress: {
    buildingName: 'FLOOR',
    buildingNumber: '1',
    line1: 'SOME_NAME',
    line2: '',
    line3: '',
    line4: 'London',
    postcode: 'POSTCODE',
    countryId: 'GB',
  },
}
