import { table, autoGeneratedHashKey, attribute, hashKey } from '@aws/dynamodb-data-mapper-annotations'
import { TABLE_NAMES } from './../constants'

@table(TABLE_NAMES.PIPELINE)
export class PipelineModel {
  @autoGeneratedHashKey()
  id?: string

  @hashKey()
  deploymentId?: string

  @attribute({ defaultProvider: () => Date() })
  created?: string

  @attribute({ defaultProvider: () => Date() })
  modified?: string
}
