import { table, autoGeneratedHashKey, attribute, hashKey } from '@aws/dynamodb-data-mapper-annotations'
import { AppTypeEnum, PackageManagerEnum, PipelineModelInterface } from '@reapit/foundations-ts-definitions'
import { TABLE_NAMES } from './../constants'

@table(TABLE_NAMES.PIPELINE)
export class PipelineModel implements PipelineModelInterface {
  @autoGeneratedHashKey()
  id?: string

  @hashKey()
  deploymentId?: string

  @attribute({ defaultProvider: () => Date() })
  created?: string

  @attribute({ defaultProvider: () => Date() })
  modified?: string

  @attribute({ defaultProvider: () => AppTypeEnum.NODE })
  appType?: AppTypeEnum

  @attribute()
  buildCommand?: string = 'build'

  @attribute({ defaultProvider: () => PackageManagerEnum.YARN })
  packageManager?: PackageManagerEnum
}
