import { table, autoGeneratedHashKey, attribute, hashKey } from '@aws/dynamodb-data-mapper-annotations'
import { TABLE_NAMES, Status } from './../constants'

export enum TaskFunction {
  BUILD = 'build',
  DEPLOY = 'deploy',
  PULL = 'pull',
}

@table(TABLE_NAMES.TASK)
export class TaskModel {
  @autoGeneratedHashKey()
  id?: string

  @hashKey()
  pipelineId?: string

  @attribute({ defaultProvider: () => Date() })
  created?: string

  @attribute({ defaultProvider: () => Date() })
  modified?: string

  @attribute()
  functionName?: TaskFunction

  @attribute()
  status?: Status
}
