export const mockApplicants = {
  pageNumber: 1,
  pageSize: 10,
  pageCount: 10,
  totalCount: 3966,
  _links: {
    self: {
      href: '/contacts/?PageNumber=1&PageSize=10',
    },
    first: {
      href: '/contacts/?PageNumber=1&PageSize=10',
    },
    next: {
      href: '/contacts/?PageNumber=2&PageSize=10',
    },
    last: {
      href: '/contacts/?PageNumber=397&PageSize=10',
    },
  },
  _embedded: [
    {
      id: 'MKT220017',
      created: '2022-03-08T09:12:20Z',
      modified: '2022-03-08T09:12:20Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Looking to move his mother back into the area',
      lastCall: '2019-11-12',
      nextCall: '2022-12-29',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 23,
      bedroomsMax: 25,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: {
        type: 'squareFeet',
        amount: 1500,
      },
      source: {
        id: 'RMV',
        type: 'source',
      },
    },
    {
      id: 'MKT220016',
      created: '2022-03-08T08:36:09Z',
      modified: '2022-03-08T08:38:12Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Area Lead 2022-03-07 10:29:44\nAm I able to view this property this upcoming week?',
      lastCall: null,
      nextCall: '2022-03-14',
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 1,
      bedroomsMax: 2,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: {
        priceFrom: 1,
        priceTo: 325000,
      },
      externalArea: null,
      internalArea: null,
      source: {
        id: 'ADV001',
        type: 'source',
      },
    },
    {
      id: 'MKT220015',
      created: '2022-03-07T19:18:45Z',
      modified: '2022-03-07T19:18:45Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Area Lead 2022-03-07 10:29:44\nAm I able to view this property this upcoming week?',
      lastCall: null,
      nextCall: '2022-03-14',
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 1,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: {
        priceFrom: 1,
        priceTo: 325000,
      },
      externalArea: null,
      internalArea: null,
      source: {
        id: 'ADV001',
        type: 'source',
      },
    },
  ],
}
