export const mockCompanies = {
  _embedded: [
    {
      id: 'MKT22000047',
      name: 'Reapit Company',
      branch: 'Oxford',
      notes: null,
      created: '2022-04-01T09:12:38.000Z',
      modified: '2022-04-19T06:11:11.000Z',
      active: false,
      vatRegistered: false,
      typeIds: ['SP'],
      supplierTypeId: null,
      workPhone: '4455667788',
      mobilePhone: null,
      email: 'example@email.com',
      address: {
        buildingNumber: '15',
        buildingName: '123',
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        postcode: 'B91 2XX',
        country: 'GB',
      },
    },
    {
      id: 'MKT22000046',
      name: 'Reapito',
      branch: 'Oxford',
      notes: null,
      created: '2022-04-01T08:57:18.000Z',
      modified: '2022-05-06T05:47:36.000Z',
      active: true,
      vatRegistered: false,
      typeIds: ['SP'],
      supplierTypeId: null,
      workPhone: '01234 567890',
      mobilePhone: null,
      email: 'example@email.com',
      address: {
        buildingNumber: '15',
        buildingName: '',
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        postcode: 'B91 2XX',
        country: 'GB',
      },
    },
    {
      id: 'MKT22000045',
      name: 'Reapit',
      branch: 'Oxford',
      notes:
        'Founded in 1997, The Reapit Group is a property software provider of CRM and property management solutions specialising in the residential real estate sector',
      created: '2022-04-01T08:56:50.000Z',
      modified: '2022-04-11T05:28:25.000Z',
      active: true,
      vatRegistered: true,
      typeIds: ['SP'],
      supplierTypeId: 'MG',
      workPhone: '01234 567890',
      mobilePhone: null,
      email: 'example@email.com',
      address: {
        buildingNumber: '15121',
        buildingName: '',
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        postcode: 'B91 2XX',
        country: 'GB',
      },
    },
    {
      id: 'RPT20000148',
      name: 'Lorem Lorem Loremmmm',
      branch: 'VNNzz Branch',
      notes:
        'Founded in 1997, The Reapit Group is a property software provider of CRM and property management solutions specialising in the residential real estate sector',
      created: '2020-08-12T07:51:45.000Z',
      modified: '2021-05-27T08:01:14.000Z',
      active: true,
      vatRegistered: true,
      typeIds: ['SP'],
      supplierTypeId: 'MG',
      workPhone: '01234 567890',
      mobilePhone: '07890 123456',
      email: 'example@email.com',
      address: {
        buildingNumber: '15',
        buildingName: '',
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        postcode: 'B91 2XX',
        country: 'GB',
      },
    },
  ],
}
