export const mockProperties = {
  _embedded: [
    {
      id: 'RPT220016',
      created: '2022-05-16T11:31:18Z',
      modified: '2022-05-16T11:31:18Z',
      type: [],
      strapline: 'test',
      description: '',
      bedrooms: 0,
      receptions: 0,
      bathrooms: 0,
      address: {
        line1: 'New Street',
        line2: '',
        line3: '',
        line4: '',
        buildingName: '',
        buildingNumber: '123',
        postcode: '',
        geolocation: {
          latitude: 52.479744,
          longitude: -1.894379,
        },
      },
      letting: null,
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      selling: {
        price: 0,
        description: 'ste',
        status: 'srats',
      },
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      _embedded: null,
      metadata: {},
    },
    {
      id: 'MKT220020',
      created: '2022-05-05T08:55:03Z',
      modified: '2022-05-05T08:55:03Z',
      type: ['house'],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'CustomValue1',
        CustomField2: true,
      },
    },
    {
      id: 'MKT220019',
      created: '2022-05-05T08:54:49Z',
      modified: '2022-05-05T08:54:49Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'CustomValue1',
        CustomField2: true,
      },
    },
    {
      id: 'MKT220018',
      created: '2022-04-19T11:49:30Z',
      modified: '2022-04-29T01:45:34Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'Test',
        CustomField2: true,
      },
    },
    {
      id: 'MKT220017',
      created: '2022-04-08T12:18:55Z',
      modified: '2022-04-08T12:20:26Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description: 'Here is my new description. Bonza!.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'CustomValue1',
        CustomField2: true,
      },
    },
    {
      id: 'MKT220016',
      created: '2022-04-01T09:39:58Z',
      modified: '2022-04-19T08:54:53Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'Testing123',
        CustomField2: false,
      },
    },
    {
      id: 'MKT220015',
      created: '2022-04-01T09:39:35Z',
      modified: '2022-04-01T09:39:35Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'CustomValue1',
        CustomField2: true,
      },
    },
    {
      id: 'MKT220014',
      created: '2022-04-01T09:38:47Z',
      modified: '2022-04-01T09:38:47Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'CustomValue1',
        CustomField2: true,
      },
    },
    {
      id: 'MKT220013',
      created: '2022-04-01T09:29:56Z',
      modified: '2022-04-01T09:29:56Z',
      type: ['house'],
      rooms: [
        {
          name: '12312',
          description: 'rwerew',
          dimensions: 'sdfsd',
        },
      ],
      strapline: 'test',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated in a much sought after residential location of Greasby, having the benefits of two separate entertaining rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      address: {
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        buildingName: '',
        buildingNumber: '15',
        postcode: 'B91 2XX',
        geolocation: {
          latitude: 52.415859,
          longitude: 1.777338,
        },
      },
      parkingSpaces: 3,
      internetAdvertising: false,
      notes: '',
      externalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      internalArea: {
        type: 'type',
        min: 2,
        max: 3,
      },
      letting: {
        status: 'srats',
        rent: 750,
        rentFrequency: 'monthly',
      },
      selling: {
        price: 250000,
        description: 'ste',
        status: 'srats',
      },
      _embedded: null,
      metadata: {
        CustomField1: 'CustomValue1',
        CustomField2: true,
      },
    },
  ],
}
