export const applicantsMock = {
  pageSize: 25,
  pageCount: 25,
  pageNumber: 1,
  totalCount: 1441,
  _links: {
    self: {
      href: '/applicants/?PageNumber=1&PageSize=25',
    },
    first: {
      href: '/applicants/?PageNumber=1&PageSize=25',
    },
    next: {
      href: '/applicants/?PageNumber=2&PageSize=25',
    },
    last: {
      href: '/applicants/?PageNumber=58&PageSize=25',
    },
  },
  _embedded: [
    {
      id: 'MKT200004',
      created: '2020-07-15T08:22:55Z',
      modified: '2020-07-30T15:40:30Z',
      marketingMode: 'renting',
      currency: 'GBP',
      active: true,
      notes: '',
      lastCall: null,
      nextCall: null,
      departmentId: 'G',
      solicitorId: null,
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: null,
      renting: {
        moveDate: '0001-01-01T00:00:00',
        term: '',
        rentFrom: 0,
        rentTo: 43333329,
        rentFrequency: 'monthly',
        furnishing: [],
      },
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['MKT'],
      negotiatorIds: ['ADV'],
      related: [
        {
          id: 'MKT20000010',
          name: 'Ms Lucy Elwood',
          type: 'contact',
          homePhone: '5353553535',
          workPhone: null,
          mobilePhone: '078761235679',
          email: 'lucy@elwood.com',
          primaryAddress: {
            buildingName: 'Flat 1',
            buildingNumber: '12',
            line1: 'Ash Tree Avenue',
            line2: 'South Brompton',
            line3: 'London',
            line4: '',
            postcode: 'SW10 9PA',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"4993CDD4CC12DE435A2E75318E338052"',
      _links: {
        self: {
          href: '/applicants/MKT200004',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=MKT200004',
        },
        offers: {
          href: '/offers/?applicantId=MKT200004',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=MKT200004',
        },
        department: {
          href: '/departments/G',
        },
        offices: {
          href: '/offices/?id=MKT',
        },
        negotiators: {
          href: '/negotiators/?id=ADV',
        },
        relationships: {
          href: '/applicants/MKT200004/relationships',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT200003',
      created: '2020-07-10T15:39:56Z',
      modified: '2020-07-23T09:01:20Z',
      marketingMode: 'renting',
      currency: 'GBP',
      active: true,
      notes: '',
      lastCall: null,
      nextCall: null,
      departmentId: 'G',
      solicitorId: null,
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: null,
      renting: {
        moveDate: '0001-01-01T00:00:00',
        term: '',
        rentFrom: 0,
        rentTo: 43333329,
        rentFrequency: 'monthly',
        furnishing: [],
      },
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['MKT'],
      negotiatorIds: ['ADV'],
      related: [
        {
          id: 'MKT20000009',
          name: 'Mr Harry James Potter',
          type: 'contact',
          homePhone: '55555555',
          workPhone: null,
          mobilePhone: null,
          email: 'harry@hogwarts.com',
          primaryAddress: {
            buildingName: '4',
            buildingNumber: '',
            line1: 'Privet Drive',
            line2: '',
            line3: '5464',
            line4: '',
            postcode: 'RH8 0EY',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"60A16372543B4C439ED4AD4F8B49CEB5"',
      _links: {
        self: {
          href: '/applicants/MKT200003',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=MKT200003',
        },
        offers: {
          href: '/offers/?applicantId=MKT200003',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=MKT200003',
        },
        department: {
          href: '/departments/G',
        },
        offices: {
          href: '/offices/?id=MKT',
        },
        negotiators: {
          href: '/negotiators/?id=ADV',
        },
        relationships: {
          href: '/applicants/MKT200003/relationships',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT200002',
      created: '2020-07-10T08:41:14Z',
      modified: '2020-07-20T10:34:08Z',
      marketingMode: 'renting',
      currency: 'GBP',
      active: true,
      notes: '',
      lastCall: null,
      nextCall: null,
      departmentId: 'G',
      solicitorId: null,
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: null,
      renting: {
        moveDate: '0001-01-01T00:00:00',
        term: '',
        rentFrom: 0,
        rentTo: 43333329,
        rentFrequency: 'monthly',
        furnishing: [],
      },
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['MKT'],
      negotiatorIds: ['ADV'],
      related: [
        {
          id: 'MKT20000007',
          name: 'Mr Freddy Bruce',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: '071234567890',
          email: 'freddy@bruce.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '',
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            postcode: '',
            countryId: 'GB',
          },
        },
        {
          id: 'MKT20000006',
          name: 'Mr Ali Venerandi',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: '071234567890',
          email: 'ali@venerandi.com',
          primaryAddress: {
            buildingName: 'Yellow House',
            buildingNumber: '',
            line1: 'Yellow Brick Road',
            line2: '',
            line3: '',
            line4: '',
            postcode: 'RH8 0EY',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"D18169E292FC14BBC6CD17C96D90F2DB"',
      _links: {
        self: {
          href: '/applicants/MKT200002',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=MKT200002',
        },
        offers: {
          href: '/offers/?applicantId=MKT200002',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=MKT200002',
        },
        department: {
          href: '/departments/G',
        },
        offices: {
          href: '/offices/?id=MKT',
        },
        negotiators: {
          href: '/negotiators/?id=ADV',
        },
        relationships: {
          href: '/applicants/MKT200002/relationships',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200029',
      created: '2020-05-20T10:58:08Z',
      modified: '2020-08-07T07:16:25Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: '',
      lastCall: null,
      nextCall: null,
      departmentId: 'G',
      solicitorId: null,
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: {
        priceFrom: 250000,
        priceTo: 300000,
      },
      renting: null,
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['RPT'],
      negotiatorIds: ['BAV'],
      related: [
        {
          id: 'RPT20000138',
          name: 'Mr Malcolm Heywood',
          type: 'contact',
          homePhone: '3243424234',
          workPhone: null,
          mobilePhone: null,
          email: 'malcom.heywood@reapitestates.net',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '',
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            postcode: '',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"616EB53605D27D3572066A3D476FE8FC"',
      _links: {
        self: {
          href: '/applicants/RPT200029',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200029',
        },
        offers: {
          href: '/offers/?applicantId=RPT200029',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200029',
        },
        department: {
          href: '/departments/G',
        },
        offices: {
          href: '/offices/?id=RPT',
        },
        negotiators: {
          href: '/negotiators/?id=BAV',
        },
        relationships: {
          href: '/applicants/RPT200029/relationships',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200027',
      created: '2020-05-18T11:49:21Z',
      modified: '2020-05-18T13:57:13Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: '',
      lastCall: null,
      nextCall: null,
      departmentId: 'G',
      solicitorId: null,
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: {
        priceFrom: 0,
        priceTo: 9999999,
      },
      renting: null,
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['RPT'],
      negotiatorIds: ['RPT'],
      related: [
        {
          id: 'RPT20000130',
          name: 'Mr Bob Asdsads',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: null,
          email: 'adasdasdasd@sadasdasd.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '',
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            postcode: '',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"1FE9DCBDC4ECFE7BE3B8DCEC8F7DE2DB"',
      _links: {
        self: {
          href: '/applicants/RPT200027',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200027',
        },
        offers: {
          href: '/offers/?applicantId=RPT200027',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200027',
        },
        department: {
          href: '/departments/G',
        },
        offices: {
          href: '/offices/?id=RPT',
        },
        negotiators: {
          href: '/negotiators/?id=RPT',
        },
        relationships: {
          href: '/applicants/RPT200027/relationships',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT200001',
      created: '2020-05-07T10:55:32Z',
      modified: '2020-06-15T13:25:07Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: '',
      lastCall: null,
      nextCall: null,
      departmentId: 'G',
      solicitorId: null,
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: {
        priceFrom: 100000,
        priceTo: 200000,
      },
      renting: null,
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['MKT'],
      negotiatorIds: ['BBB'],
      related: [
        {
          id: 'MKT20000001',
          name: 'Test Holly Phillips',
          type: 'contact',
          homePhone: '01287 999 9789',
          workPhone: null,
          mobilePhone: null,
          email: 'hphillips@reapit.com',
          primaryAddress: {
            buildingName: '123',
            buildingNumber: '15',
            line1: 'Furzen Crescent',
            line2: 'Hatfield',
            line3: 'Herfordshire',
            line4: '',
            postcode: 'AL10 9QN',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"0AE4F799960782830E3DF42A5C79B73A"',
      _links: {
        self: {
          href: '/applicants/MKT200001',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=MKT200001',
        },
        offers: {
          href: '/offers/?applicantId=MKT200001',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=MKT200001',
        },
        department: {
          href: '/departments/G',
        },
        offices: {
          href: '/offices/?id=MKT',
        },
        negotiators: {
          href: '/negotiators/?id=BBB',
        },
        relationships: {
          href: '/applicants/MKT200001/relationships',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200026',
      created: '2020-04-28T08:01:48Z',
      modified: '2020-04-28T08:01:51Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000125',
          name: 'Bloggs',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: null,
          email: 'joe@bloggs.com',
          primaryAddress: null,
        },
      ],
      metadata: {},
      _eTag: '"D9F28559D6D1E4510340EA1A22346E4F"',
      _links: {
        self: {
          href: '/applicants/RPT200026',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200026',
        },
        offers: {
          href: '/offers/?applicantId=RPT200026',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200026',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200026/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200025',
      created: '2020-04-27T08:00:59Z',
      modified: '2020-04-27T08:01:02Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000124',
          name: 'Bloggs',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: null,
          email: 'joe@bloggs.com',
          primaryAddress: null,
        },
      ],
      metadata: {},
      _eTag: '"6D20D8D9BDB1E71BE312E7D48DE7BEF6"',
      _links: {
        self: {
          href: '/applicants/RPT200025',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200025',
        },
        offers: {
          href: '/offers/?applicantId=RPT200025',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200025',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200025/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200024',
      created: '2020-04-26T08:01:02Z',
      modified: '2020-04-26T08:01:06Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000116',
          name: 'Test',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: null,
          email: 'testcontact@test.com',
          primaryAddress: null,
        },
      ],
      metadata: {},
      _eTag: '"8A91A4113BAD03ADA341579204CD5A85"',
      _links: {
        self: {
          href: '/applicants/RPT200024',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200024',
        },
        offers: {
          href: '/offers/?applicantId=RPT200024',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200024',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200024/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200023',
      created: '2020-04-25T08:01:00Z',
      modified: '2020-04-25T08:01:03Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000115',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"ED31A746F1C42D4704FD14304A7476DF"',
      _links: {
        self: {
          href: '/applicants/RPT200023',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200023',
        },
        offers: {
          href: '/offers/?applicantId=RPT200023',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200023',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200023/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200022',
      created: '2020-04-24T08:00:58Z',
      modified: '2020-04-24T08:01:01Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000112',
          name: 'Test',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: null,
          email: 'testcontact@test.com',
          primaryAddress: null,
        },
      ],
      metadata: {},
      _eTag: '"68F0BF9CB529FD17ABA8A025B97D040C"',
      _links: {
        self: {
          href: '/applicants/RPT200022',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200022',
        },
        offers: {
          href: '/offers/?applicantId=RPT200022',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200022',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200022/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200021',
      created: '2020-04-23T08:06:38Z',
      modified: '2020-04-23T08:06:41Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000097',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"BAF9F2037A72083461193A080099CA93"',
      _links: {
        self: {
          href: '/applicants/RPT200021',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200021',
        },
        offers: {
          href: '/offers/?applicantId=RPT200021',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200021',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200021/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200020',
      created: '2020-04-23T08:01:05Z',
      modified: '2020-04-23T08:01:09Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000095',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"D5475854A1C5D6C104D5E54CB8B37105"',
      _links: {
        self: {
          href: '/applicants/RPT200020',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200020',
        },
        offers: {
          href: '/offers/?applicantId=RPT200020',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200020',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200020/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200019',
      created: '2020-04-22T08:01:01Z',
      modified: '2020-04-22T08:01:04Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000093',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"489E080E6CC4A39C8A5CAA167E83E66B"',
      _links: {
        self: {
          href: '/applicants/RPT200019',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200019',
        },
        offers: {
          href: '/offers/?applicantId=RPT200019',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200019',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200019/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200018',
      created: '2020-04-21T08:01:06Z',
      modified: '2020-04-21T08:01:09Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000091',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"02FCADB4E3E361E16477A9B8E9CFD7A4"',
      _links: {
        self: {
          href: '/applicants/RPT200018',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200018',
        },
        offers: {
          href: '/offers/?applicantId=RPT200018',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200018',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200018/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200017',
      created: '2020-04-20T08:01:05Z',
      modified: '2020-04-20T08:01:08Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000089',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"6D6BA2EA7F29891B81886004C2C8E40A"',
      _links: {
        self: {
          href: '/applicants/RPT200017',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200017',
        },
        offers: {
          href: '/offers/?applicantId=RPT200017',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200017',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200017/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200016',
      created: '2020-04-19T08:01:01Z',
      modified: '2020-04-19T08:01:04Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000087',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: null,
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: '',
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"98B3835DB718A241DA194B46253386A8"',
      _links: {
        self: {
          href: '/applicants/RPT200016',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200016',
        },
        offers: {
          href: '/offers/?applicantId=RPT200016',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200016',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200016/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200015',
      created: '2020-04-18T08:01:03Z',
      modified: '2020-04-18T08:01:06Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000086',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"555C07B767045F8027E1E66EA665C5B3"',
      _links: {
        self: {
          href: '/applicants/RPT200015',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200015',
        },
        offers: {
          href: '/offers/?applicantId=RPT200015',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200015',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200015/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200014',
      created: '2020-04-17T08:01:21Z',
      modified: '2020-04-17T08:01:24Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000082',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"4E8A8D291E647A403CA6E1A23499065E"',
      _links: {
        self: {
          href: '/applicants/RPT200014',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200014',
        },
        offers: {
          href: '/offers/?applicantId=RPT200014',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200014',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200014/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200013',
      created: '2020-04-16T08:00:58Z',
      modified: '2020-04-16T08:01:01Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000080',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"5A68E7D2A696F870D131E98798859B70"',
      _links: {
        self: {
          href: '/applicants/RPT200013',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200013',
        },
        offers: {
          href: '/offers/?applicantId=RPT200013',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200013',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200013/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200012',
      created: '2020-04-15T08:01:07Z',
      modified: '2020-04-15T08:01:10Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000078',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '132132131',
          workPhone: null,
          mobilePhone: null,
          email: 'nha.le@yopmail.com',
          primaryAddress: {
            buildingName: '123',
            buildingNumber: 'áedsa',
            line1: 'Example street',
            line2: '1',
            line3: 'West Midlands',
            line4: '',
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"8EB6E98405A19461AE5EFD36824247C6"',
      _links: {
        self: {
          href: '/applicants/RPT200012',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200012',
        },
        offers: {
          href: '/offers/?applicantId=RPT200012',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200012',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200012/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200011',
      created: '2020-04-14T11:26:03Z',
      modified: '2020-04-14T11:26:07Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000076',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"C07CAC10E9199D0BBA02E1ABAB41338F"',
      _links: {
        self: {
          href: '/applicants/RPT200011',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200011',
        },
        offers: {
          href: '/offers/?applicantId=RPT200011',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200011',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200011/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200010',
      created: '2020-03-10T10:01:20Z',
      modified: '2020-03-10T10:01:20Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Looking to move his mother back into the area',
      lastCall: '2019-11-12',
      nextCall: '2019-12-29',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: {
        type: 'squareFeet',
        amount: 1500,
      },
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000076',
          name: 'Mr John Smith',
          type: 'contact',
          homePhone: '01234 567890',
          workPhone: '01234 567890',
          mobilePhone: '07890 123456',
          email: 'example@email.com',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '15',
            line1: 'Example street',
            line2: 'Solihull',
            line3: 'West Midlands',
            line4: null,
            postcode: 'B91 2XX',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"4AEAC9C7AB9EDA981189802F71A14200"',
      _links: {
        self: {
          href: '/applicants/RPT200010',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200010',
        },
        offers: {
          href: '/offers/?applicantId=RPT200010',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200010',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200010/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200009',
      created: '2020-03-10T09:44:52Z',
      modified: '2020-08-10T09:35:06Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: '2019-11-12',
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'OXF18000012',
      type: ['house', 'maisonette', 'cottage'],
      style: ['detached', 'semiDetached'],
      situation: ['garden', 'patio'],
      parking: ['garage'],
      age: ['period'],
      locality: ['rural'],
      bedroomsMin: 4,
      bedroomsMax: 5,
      receptionsMin: 1,
      receptionsMax: 2,
      bathroomsMin: 1,
      bathroomsMax: 0,
      locationType: 'areas',
      locationOptions: ['SOL', 'BHM', 'WLV'],
      buying: {
        priceFrom: 250000,
        priceTo: 275000,
      },
      renting: null,
      externalArea: {
        type: 'acres',
        amountFrom: 2,
        amountTo: 3,
      },
      internalArea: null,
      source: {
        id: 'RMV',
        type: 'source',
      },
      officeIds: ['OXF', 'SOL'],
      negotiatorIds: ['JAS'],
      related: [
        {
          id: 'RPT20000074',
          name: 'Billye Zulauf',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: '07885975749',
          email: 'albert@haley.biz',
          primaryAddress: null,
        },
        {
          id: 'MKT20000051',
          name: 'Zul',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: '07777777777',
          email: 'jzulauf@localhost',
          primaryAddress: {
            buildingName: '',
            buildingNumber: '',
            line1: '',
            line2: '',
            line3: '',
            line4: '',
            postcode: '',
            countryId: 'GB',
          },
        },
      ],
      metadata: {},
      _eTag: '"DCA0EDC7F2D15753DC1F7141EEB31486"',
      _links: {
        self: {
          href: '/applicants/RPT200009',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200009',
        },
        offers: {
          href: '/offers/?applicantId=RPT200009',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200009',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/OXF18000012',
        },
        offices: {
          href: '/offices/?id=OXF&id=SOL',
        },
        negotiators: {
          href: '/negotiators/?id=JAS',
        },
        relationships: {
          href: '/applicants/RPT200009/relationships',
        },
        areas: {
          href: '/areas/?id=SOL&id=BHM&id=WLV',
        },
        source: {
          href: '/sources/RMV',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT200008',
      created: '2020-03-03T13:08:23Z',
      modified: '2020-05-29T11:31:09Z',
      marketingMode: 'buying',
      currency: 'GBP',
      active: true,
      notes: 'Some updated notes',
      lastCall: null,
      nextCall: '2020-12-01',
      departmentId: 'G',
      solicitorId: 'TWC10001654',
      type: [],
      style: [],
      situation: [],
      parking: [],
      age: [],
      locality: [],
      bedroomsMin: 0,
      bedroomsMax: 0,
      receptionsMin: 0,
      receptionsMax: 0,
      bathroomsMin: 0,
      bathroomsMax: 0,
      locationType: 'none',
      locationOptions: [],
      buying: {
        priceFrom: 1,
        priceTo: 0,
      },
      renting: null,
      externalArea: null,
      internalArea: null,
      source: null,
      officeIds: ['REA'],
      negotiatorIds: ['MGL'],
      related: [
        {
          id: 'RPT20000073',
          name: 'Billye Zulauf',
          type: 'contact',
          homePhone: null,
          workPhone: null,
          mobilePhone: '07885975749',
          email: 'albert@haley.biz',
          primaryAddress: null,
        },
      ],
      metadata: {},
      _eTag: '"922311B628001C1163CF4DDFCB052E20"',
      _links: {
        self: {
          href: '/applicants/RPT200008',
        },
        documents: {
          href: '/documents/?associatedType=applicant&associatedId=RPT200008',
        },
        offers: {
          href: '/offers/?applicantId=RPT200008',
        },
        appointments: {
          href: '/appointments/?attendeeType=applicant&attendeeId=RPT200008',
        },
        department: {
          href: '/departments/G',
        },
        solicitor: {
          href: '/companies/TWC10001654',
        },
        offices: {
          href: '/offices/?id=REA',
        },
        negotiators: {
          href: '/negotiators/?id=MGL',
        },
        relationships: {
          href: '/applicants/RPT200008/relationships',
        },
      },
      _embedded: null,
    },
  ],
}
