service: cloud-deploy-slack-bot
plugins:
  - serverless-offline
  - serverless-deployment-bucket

custom:
  s3CloudFormBucket: cloud-deploy-slack-bot-${opt:stage, 'dev'}
  env: ${file(./config.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  deploymentBucket:
    name: ${self:custom.s3CloudFormBucket}
  environment:
    NODE_ENV: 'production'
    REPO_DISPATCH_API: ${self:custom.env.REPO_DISPATCH_API}
    GITHUB_TOKEN: ${self:custom.env.GITHUB_TOKEN}
    SLACK_BOT_HOOK: ${self:custom.env.SLACK_BOT_HOOK}
    SLACK_BOT_SIGNING_SECRET: ${self:custom.env.SLACK_BOT_SIGNING_SECRET}

package:
  individually: true
  include:
    - dist/**
    - node_modules/**
    - config.json
  exclude:
    - package.json
    - node_modules/**
    - error.log
    - info.log
    - jest.config.js
    - nodemon.json
    - serverless.yml
    - src/**
    - tsconfig.json
    - yml-helpers.js

functions:
  deploy-slack-bot:
    handler: dist/index.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
      - http:
          method: any
          path: /
          cors: true

