import { PaymentApiKeyInterface, DeploymentApiKeyInterface, KeyType } from "@reapit/foundations-ts-definitions"
import { attribute, table, autoGeneratedHashKey } from '@aws/dynamodb-data-mapper-annotations'
import { TABLE_NAMES } from './../constants'

@table(TABLE_NAMES.API_KEY_TABLE)
export class ApiKeyModel implements DeploymentApiKeyInterface, PaymentApiKeyInterface {
	@autoGeneratedHashKey()
	apiKey: string

	@attribute()
	organisationId?: string

	@attribute()
	developerId: string

	@attribute({ defaultProvider: () => new Date().toISOString() })
	keyCreatedAt: string

	@attribute()
	keyExpiresAt: string

	@attribute()
	clientCode: string

	@attribute()
	keyType: KeyType

	@attribute()
	paymentId: string
}
