import { attribute, autoGeneratedHashKey, table, rangeKey } from '@aws/dynamodb-data-mapper-annotations'
import { TABLE_NAMES } from '../constants'

@table(TABLE_NAMES.DEPLOYMENT)
export class DeploymentModel {
  @autoGeneratedHashKey()
  apiKey?: string

  @attribute()
  name?: string

  @attribute()
  organisationId?: string

  @rangeKey({ defaultProvider: () => new Date() })
  created?: string

  @attribute()
  modified?: string

  @attribute()
  developerId?: string
}
