import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations'
import { TABLE_NAMES } from '@/constants'

@table(TABLE_NAMES.DEPLOYMENT)
export class DeploymentModel {
  @autoGeneratedHashKey()
  id?: string

  @attribute()
  name?: string

  @attribute()
  organisationId?: string

  @attribute({ defaultProvider: () => new Date() })
  created?: string

  @attribute({ defaultProvider: () => new Date() })
  modified?: string

  @attribute()
  developerId?: string
}
