import { attribute, autoGeneratedHashKey, table } from '@aws/dynamodb-data-mapper-annotations'
import { TABLE_NAMES } from '@/constants'
import { AppTypeEnum, PackageManagerEnum } from '../dto'
import { PipelineModelInterface } from '../../../foundations-ts-definitions/deployment-schema'

@table(TABLE_NAMES.PIPELINE)
export class PipelineModel implements PipelineModelInterface {
  @autoGeneratedHashKey()
  id?: string

  @attribute()
  name?: string

  @attribute({ defaultProvider: () => new Date() })
  created?: string

  @attribute({ defaultProvider: () => new Date() })
  modified?: string

  @attribute()
  developerId?: string

  @attribute()
  appType?: AppTypeEnum

  @attribute()
  buildCommand?: string = 'build'

  @attribute({ defaultProvider: () => PackageManagerEnum.YARN })
  packageManager?: PackageManagerEnum

  @attribute()
  repository?: string
}
