import { WizardStep } from './types'

export const wizzardSteps: Record<WizardStep, WizardStep> = {
  SUBMIT_APP_SUCCESS: 'SUBMIT_APP_SUCCESS',
  INPUT_AUTHENTICATION_URIS: 'INPUT_AUTHENTICATION_URIS',
  INPUT_ATHENTICATION_TYPE: 'INPUT_ATHENTICATION_TYPE',
  INPUT_APP_NAME: 'INPUT_APP_NAME',
  GRANT_PERMISSION: 'GRANT_PERMISSION',
  CREATE_NEW_APP: 'CREATE_NEW_APP',
  BEFORE_YOU_START: 'BEFORE_YOU_START',
}
