export const white = '#fff'
export const black = '#3b454e'
export const grey = '#74818d'
export const greyLight = '#f5f7f9'

export const greenLighter = '#acf2bd'
export const greenLightest = '#e6ffed'
export const redLighter = '#fdb8c0'
export const redLightest = '#ffeef0'

export const reapitDarkblue = '#262f69'
export const reapitDarkblueDrakened = '#1e2554'
export const reapitMidblue = '#0061a8'
export const reapitLightblue = '#23a4de'
export const reapitLightestblue = '#7bc9eb'

export const reapitOrange = '#ec631b'
export const reapitLime = '#cddb00'
export const reapitTeal = '#006580'
export const reapitPlumb = '#7a2c81'
export const reapitPurple = '#a4185c'
export const reapitGold = '#ffb71b'
export const reapitGreen = '#a0c862'
export const reapitRed = '#d3033d'
