// layout
export const layoutBase = '1rem'
export const layoutQuarter = 'calc(1rem / 4)'
export const layoutThird = 'calc(1rem / 3)'
export const layoutHalf = 'calc(1rem / 2)'
export const layoutTwoThird = 'calc(1rem * 0.67)'
export const layoutThreeQuarter = 'calc(1rem * 0.75)'
export const layoutOneQuarter = 'calc(1rem * 1.25)'
export const layoutOneHalf = 'calc(1rem * 1.5)'
export const layoutDouble = 'calc(1rem * 2)'
export const layoutTwoHalf = 'calc(1rem * 2.5)'
export const layoutTriple = 'calc(1rem * 3)'
export const layoutQuadruple = 'calc(1rem * 4)'
export const layoutSextuple = 'calc(1rem * 6)'
