export const forSmallMobileOnly = '@media (max-width: 414px)'
export const forMobileOnly = '@media (max-width: 768px)'
export const forTabletAndBelow = '@media (max-width: 1023px)'
export const forTabletOnly = '@media (min-width: 769px) and (max-width: 1023px)'
export const forTabletAndDesktop = '@media (min-width: 769px)'
export const forDesktopOnly = '@media (min-width: 1024px)'
