import { attribute, table, autoGeneratedHashKey } from '@aws/dynamodb-data-mapper-annotations'

@table(process.env.DYNAMO_DB_PAYMENTS_SESSION_TABLE_NAME ?? 'Cloud_Payments_Session_Table')
export class SessionModel {
  @autoGeneratedHashKey()
  id: string

  @attribute({ defaultProvider: () => new Date().toISOString() })
  sessionCreatedAt: string

  @attribute()
  sessionExpiresAt: string

  @attribute()
  clientCode: string

  @attribute()
  paymentId: string

  sessionIsValid(clientCode?: string, paymentId?: string): boolean {
    const isCurrent = new Date(this.sessionExpiresAt as string) > new Date()
    const paymentIdValid = paymentId && paymentId === this.paymentId
    const clientCodeValid = clientCode && clientCode === this.clientCode

    return isCurrent && paymentIdValid && clientCodeValid
  }
}
