import { attribute, table, autoGeneratedHashKey } from '@aws/dynamodb-data-mapper-annotations'

@table(process.env.DYNAMO_DB_PAYMENTS_SESSION_TABLE_NAME)
export class SessionModel {
  @autoGeneratedHashKey()
  id: string

  @attribute({ defaultProvider: () => new Date().toISOString() })
  sessionCreatedAt: string

  @attribute()
  sessionExpiresAt: string

  @attribute()
  clientCode: string

  @attribute()
  paymentId: string

  get expired(): boolean {
    return new Date(this.sessionExpiresAt as string) < new Date()
  }
}
