export const webComponentConfigs = [
  {
    configuration: {
      timeIntervalMinutes: 10,
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      country: 'GB',
      months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      appointmentGapMinutes: 10,
    },
    clientId: '1',
    clientWebsite: 'www.google.com',
  },
  {
    configuration: {
      timeIntervalMinutes: 10,
      days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
      country: 'GB',
      months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
      appointmentGapMinutes: 10,
    },
    clientId: '2',
    clientWebsite: 'www.google.com',
  },
]
