export const tasksMock = {
  pageNumber: 1,
  pageSize: 25,
  pageCount: 25,
  totalCount: 10693,
  _links: {
    self: {
      href: '/tasks/?PageNumber=1&PageSize=25',
    },
    first: {
      href: '/tasks/?PageNumber=1&PageSize=25',
    },
    next: {
      href: '/tasks/?PageNumber=2&PageSize=25',
    },
    last: {
      href: '/tasks/?PageNumber=428&PageSize=25',
    },
  },
  _embedded: [
    {
      id: 'MKT2000021',
      created: '2020-07-30T13:46:12Z',
      modified: '2020-08-03T15:59:12Z',
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'ADV',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"D27B20728E6B8F171C6E59E1B492B61E"',
      _links: {
        self: {
          href: '/tasks/MKT2000021',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/ADV',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000020',
      created: '2020-07-30T13:46:12Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'JES',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"B17D8635B24357E10CB9EE87E19B856C"',
      _links: {
        self: {
          href: '/tasks/MKT2000020',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/JES',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000019',
      created: '2020-07-30T13:46:12Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'AXG',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"FE79673A07E86F2615A8DA63F8141137"',
      _links: {
        self: {
          href: '/tasks/MKT2000019',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/AXG',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000018',
      created: '2020-07-30T13:46:12Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'GLR',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"FF30AD79ADDFD4AD59CFB9DFD9FB95CB"',
      _links: {
        self: {
          href: '/tasks/MKT2000018',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/GLR',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000017',
      created: '2020-07-30T13:46:11Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'JOSM',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"6652DE5F5DF4DB0422B86732BF021374"',
      _links: {
        self: {
          href: '/tasks/MKT2000017',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/JOSM',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000016',
      created: '2020-07-30T13:45:48Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'AACB',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"E0EFD42F42C75C920A7BA99CA0447A2C"',
      _links: {
        self: {
          href: '/tasks/MKT2000016',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/AACB',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000015',
      created: '2020-07-30T13:45:46Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'RJN',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"9B21F9581741E82B73B252597D2D5C98"',
      _links: {
        self: {
          href: '/tasks/MKT2000015',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/RJN',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000014',
      created: '2020-07-30T13:45:44Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'JSH',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"4D30AC38950C03841F248056EA09DB81"',
      _links: {
        self: {
          href: '/tasks/MKT2000014',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/JSH',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000013',
      created: '2020-07-30T13:45:43Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'PJT',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"453512D88062F89BF5633D922F3055FD"',
      _links: {
        self: {
          href: '/tasks/MKT2000013',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/PJT',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000012',
      created: '2020-07-30T13:45:42Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'JNS',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"D988717633848FB2EDED6A785ADE0716"',
      _links: {
        self: {
          href: '/tasks/MKT2000012',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/JNS',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000011',
      created: '2020-07-30T13:45:41Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'CLG',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"FBB56F19D8F99AFE7BEE2DA9743053D8"',
      _links: {
        self: {
          href: '/tasks/MKT2000011',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/CLG',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000010',
      created: '2020-07-30T13:45:40Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'ECS',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"4A36EE996A8411A715128E5A611B1AF4"',
      _links: {
        self: {
          href: '/tasks/MKT2000010',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/ECS',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000009',
      created: '2020-07-30T13:45:38Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'CBM',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"950645DDE17FFF1F5AA338C1FAB67144"',
      _links: {
        self: {
          href: '/tasks/MKT2000009',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/CBM',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000008',
      created: '2020-07-30T13:45:37Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'PMH',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"C87ED8838B4D5CC3E320287927E69F40"',
      _links: {
        self: {
          href: '/tasks/MKT2000008',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/PMH',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000007',
      created: '2020-07-30T13:45:35Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'FRED',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"7B348F63F9F6050952B04F03191F9274"',
      _links: {
        self: {
          href: '/tasks/MKT2000007',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/FRED',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000006',
      created: '2020-07-30T13:45:32Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'CRF',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"793C9198E0A5EDFC793E2BDAE317F140"',
      _links: {
        self: {
          href: '/tasks/MKT2000006',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/CRF',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000005',
      created: '2020-07-30T13:45:31Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'GJL',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"F19B4D457F3344A19B27D5370DED7843"',
      _links: {
        self: {
          href: '/tasks/MKT2000005',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/GJL',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000004',
      created: '2020-07-30T13:45:30Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'OCH',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"45F82B0AB9477FE856E0CD6AE6121761"',
      _links: {
        self: {
          href: '/tasks/MKT2000004',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/OCH',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000003',
      created: '2020-07-30T13:45:28Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'AJM',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"94028E053985F7E1DD76B8E269D0E8D4"',
      _links: {
        self: {
          href: '/tasks/MKT2000003',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/AJM',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000002',
      created: '2020-07-30T13:45:26Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'ANYU',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"854A8367CDBC4645D35646D25B5526B3"',
      _links: {
        self: {
          href: '/tasks/MKT2000002',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/ANYU',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'MKT2000001',
      created: '2020-07-30T13:45:25Z',
      modified: null,
      activates: '2020-07-30',
      completed: null,
      typeId: 'RM',
      senderId: 'ADV',
      text: 'hello just seeing how this works thanks',
      landlordId: '',
      propertyId: '',
      applicantId: '',
      tenancyId: '',
      contactId: 'MLK12000004',
      recipientId: 'ALPE',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"72018741A969E2F09F0CC19F17016464"',
      _links: {
        self: {
          href: '/tasks/MKT2000001',
        },
        sender: {
          href: '/negotiators/ADV',
        },
        recipient: {
          href: '/negotiators/ALPE',
        },
        type: {
          href: '/configuration/taskTypes/RM',
        },
        contact: {
          href: '/contacts/MLK12000004',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT2000020',
      created: '2020-05-18T13:20:48Z',
      modified: '2020-05-18T13:23:06Z',
      activates: '2020-05-18',
      completed: '2020-05-18',
      typeId: '',
      senderId: 'RPT',
      text: '1231231',
      landlordId: '',
      propertyId: 'BDF110362',
      applicantId: '',
      tenancyId: '',
      contactId: '',
      recipientId: 'RPT',
      recipientType: 'negotiator',
      metadata: {
        CustomTaskField2: true,
        CustomTaskField1: 'yes',
      },
      _eTag: '"3EF4A6455FFD229C431D62996433C482"',
      _links: {
        self: {
          href: '/tasks/RPT2000020',
        },
        sender: {
          href: '/negotiators/RPT',
        },
        recipient: {
          href: '/negotiators/RPT',
        },
        property: {
          href: '/properties/BDF110362',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT2000019',
      created: '2020-05-14T09:39:24Z',
      modified: '2020-05-14T09:40:41Z',
      activates: '2020-05-14',
      completed: null,
      typeId: 'ET',
      senderId: 'RPT',
      text: 'asdassss',
      landlordId: '',
      propertyId: 'BDF140729',
      applicantId: '',
      tenancyId: '',
      contactId: 'BCK14000690',
      recipientId: 'RPT',
      recipientType: 'negotiator',
      metadata: {},
      _eTag: '"FBBD6D7EF5651DBC992002194AE8911C"',
      _links: {
        self: {
          href: '/tasks/RPT2000019',
        },
        sender: {
          href: '/negotiators/RPT',
        },
        recipient: {
          href: '/negotiators/RPT',
        },
        type: {
          href: '/configuration/taskTypes/ET',
        },
        property: {
          href: '/properties/BDF140729',
        },
        contact: {
          href: '/contacts/BCK14000690',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT2000018',
      created: '2020-04-28T08:02:29Z',
      modified: '2020-04-28T08:02:29Z',
      activates: '2019-05-12',
      completed: '2019-07-05',
      typeId: 'MI',
      senderId: 'JAS',
      text: 'Arrange for bathroom photos to be retaken',
      landlordId: '',
      propertyId: 'OXF123022',
      applicantId: '',
      tenancyId: '',
      contactId: '',
      recipientId: 'OXF',
      recipientType: 'office',
      metadata: {},
      _eTag: '"EEEFAE764289044ABC30CFB06C7339ED"',
      _links: {
        self: {
          href: '/tasks/RPT2000018',
        },
        sender: {
          href: '/negotiators/JAS',
        },
        recipient: {
          href: '/offices/OXF',
        },
        type: {
          href: '/configuration/taskTypes/MI',
        },
        property: {
          href: '/properties/OXF123022',
        },
      },
      _embedded: null,
    },
    {
      id: 'RPT2000017',
      created: '2020-04-27T08:01:36Z',
      modified: '2020-04-27T08:01:36Z',
      activates: '2019-05-12',
      completed: '2019-07-05',
      typeId: 'MI',
      senderId: 'JAS',
      text: 'Arrange for bathroom photos to be retaken',
      landlordId: '',
      propertyId: 'OXF123022',
      applicantId: '',
      tenancyId: '',
      contactId: '',
      recipientId: 'OXF',
      recipientType: 'office',
      metadata: {},
      _eTag: '"AEB048199C1AC7B51F9FB8C3003EF7F5"',
      _links: {
        self: {
          href: '/tasks/RPT2000017',
        },
        sender: {
          href: '/negotiators/JAS',
        },
        recipient: {
          href: '/offices/OXF',
        },
        type: {
          href: '/configuration/taskTypes/MI',
        },
        property: {
          href: '/properties/OXF123022',
        },
      },
      _embedded: null,
    },
  ],
}
