export const updateApplicantArgsMock = {
  id: 'MKT200004',
  marketingMode: 'buying',
  active: true,
  notes: 'Looking to move his mother back into the area',
  lastCall: '2019-11-12',
  nextCall: '2019-12-29',
  departmentId: 'G',
  solicitorId: 'OXF18000012',
  type: ['house', 'maisonette', 'cottage'],
  style: ['detached', 'semiDetached'],
  situation: ['garden', 'patio'],
  parking: ['garage'],
  age: ['period'],
  locality: ['rural'],
  bedroomsMin: 4,
  bedroomsMax: 5,
  receptionsMin: 1,
  receptionsMax: 2,
  bathroomsMin: 1,
  bathroomsMax: null,
  locationType: 'areas',
  locationOptions: ['SOL', 'BHM', 'WLV'],
  buying: {
    priceFrom: 250000,
    priceTo: 275000,
  },
  renting: null,
  externalArea: {
    type: 'acres',
    amountFrom: 2,
    amountTo: 3,
  },
  internalArea: {
    type: 'squareFeet',
    amount: 1500,
  },
  source: {
    id: 'RMV',
    type: 'source',
  },
  officeIds: ['OXF', 'SOL'],
  negotiatorIds: ['JAS'],
  metadata: {},
  _eTag: '"909A2F6137DC77F82CB6AD6BAF76DE11"',
}
