service: cloud-graphql-server
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-deployment-bucket

custom:
  s3CloudFormBucket: cloud-deployment-cloudform-templates-${opt:stage, 'dev'}
  env: ${file(./config.json)}
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
    packagerOptions:
      noFrozenLockFile: false
    excludeFiles: src/**/*.test.ts
    keepOutputDirectory: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL
  region: eu-west-2
  deploymentBucket:
    name: ${self:custom.s3CloudFormBucket}
    blockPublicAccess: false

  environment:
    NODE_ENV: 'production'
    COGNITO_USERPOOL_ID: ${self:custom.env.COGNITO_USERPOOL_ID}
    MARKETPLACE_API_BASE_URL: ${self:custom.env.MARKETPLACE_API_BASE_URL}
    PLATFORM_API_BASE_URL: ${self:custom.env.PLATFORM_API_BASE_URL}
    SENTRY_DSN: ${self:custom.env.SENTRY_DSN}

package:
  individually: true
  include:
    - dist/**
  exclude:
    - package.json
    - node_modules/**
    - error.log
    - info.log
    - jest.config.js
    - nodemon.json
    - serverless.yml
    - src/**
    - tsconfig.json
    - yml-helpers.js

functions:
  graphqlHandler:
    handler: src/index.graphqlHandler
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
