export const MOBILE_BREAKPOINT = 768
export const TABLET_BREAKPOINT = 1024
export const DESKTOP_BREAKPOINT = 1440
export const WIDESCREEN_BREAKPOINT = 1920
export const SUPER_WIDESCREEN_BREAKPOINT = 2560
