import { PropertyModel } from '@reapit/foundations-ts-definitions'
import { PickedPropertyModel } from '../../../types'

export const propertyStub: PropertyModel = {
  id: 'RPT200112',
  created: '2020-04-05T08:01:36.0000000Z',
  modified: '2020-04-05T08:01:49.0000000Z',
  marketingMode: 'sellingAndLetting',
  currency: 'GBP',
  address: {
    buildingName: '',
    buildingNumber: '15',
    line1: 'Example street',
    line2: 'Solihull',
    line3: 'West Midlands',
    line4: '',
    postcode: 'B91 2XX',
    countryId: 'GB',
    geolocation: { latitude: 52.415859, longitude: 1.777338 },
  },
  areaId: 'BRM',
  strapline: '',
  description: `We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY 
    situated in a much sought after residential location of Greasby, having the benefits of two 
    separate entertaining rooms, morning room, extended kitchen. To the first floor there are three 
    bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.`,
  summary: '',
  departmentId: 'G',
  negotiatorId: 'JAS',
  bedrooms: 4,
  receptions: 1,
  bathrooms: 2,
  councilTax: 'A',
  internetAdvertising: true,
  viewingArrangements: 'Accompanied viewings after 3PM only',
  videoUrl: '',
  videoCaption: '',
  externalArea: { type: 'acres', min: 1, max: 2 },
  internalArea: { type: 'squareFeet', min: 1500, max: 2000 },
  epc: { exempt: false, eer: 45, eerPotential: 71, eir: 53, eirPotential: 81 },
  selling: {
    instructed: '2018-11-18',
    price: 250000,
    qualifier: 'askingPrice',
    status: 'underOffer',
    completed: '',
    exchanged: '',
    tenure: { type: 'leasehold', expiry: '2019-05-01' },
    vendorId: 'RPT200112',
  },
  letting: {
    instructed: '2018-11-18',
    availableFrom: '2018-12-26',
    availableTo: '2019-03-23',
    rent: 750,
    rentFrequency: 'monthly',
    furnishing: [],
    term: 'long',
    status: 'toLet',
    agentRole: '',
    landlordId: '',
  },
  type: ['house'],
  style: ['detached'],
  situation: ['garden', 'land', 'patio'],
  parking: ['doubleGarage'],
  age: ['period'],
  locality: ['rural', 'village'],
  rooms: [],
  officeIds: ['OXF', 'SOL'],
  metadata: {},
  _eTag: '"0E8D3076D0B8970CCAA52E5E95F61EF4"',
  _links: {
    self: { href: '/properties/RPT200112' },
    images: { href: '/propertyImages/?propertyId=RPT200112' },
    documents: { href: '/documents/?associatedType=property&associatedId=RPT200112' },
    offers: { href: '/offers/?propertyId=RPT200112' },
    negotiator: { href: '/negotiators/JAS' },
    offices: { href: '/offices/?id=OXF&id=SOL' },
    department: { href: '/departments/G' },
    vendor: { href: '/vendors/RPT200112' },
    area: { href: '/areas/BRM' },
  },
  _embedded: undefined,
}

export const propertyMinimalStub: PickedPropertyModel = {
  id: 'RPT200112',
  marketingMode: 'sellingAndLetting',
  address: {
    buildingName: '',
    buildingNumber: '15',
    line1: 'Example street',
    line2: 'Solihull',
    line3: 'West Midlands',
    line4: '',
    postcode: 'B91 2XX',
    countryId: 'GB',
    geolocation: { latitude: 52.415859, longitude: 1.777338 },
  },
  description: `We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY 
  situated in a much sought after residential location of Greasby, having the benefits of two 
  separate entertaining rooms, morning room, extended kitchen. To the first floor there are three 
  bedrooms, spacious family bathroom, gas central heating gardens front and rear and off road parking.`,
  bedrooms: 4,
  bathrooms: 2,
  selling: {
    instructed: '2018-11-18',
    price: 250000,
    qualifier: 'askingPrice',
    status: 'underOffer',
    completed: '',
    exchanged: '',
    tenure: { type: 'leasehold', expiry: '2019-05-01' },
    vendorId: 'RPT200112',
  },
  letting: {
    instructed: '2018-11-18',
    availableFrom: '2018-12-26',
    availableTo: '2019-03-23',
    rent: 750,
    rentFrequency: 'monthly',
    furnishing: [],
    term: 'long',
    status: 'toLet',
    agentRole: '',
    landlordId: '',
  },
  type: ['house'],
  style: ['detached'],
}
