import { PagedResultPropertyModel_ } from '@reapit/foundations-ts-definitions'

export const propertiesStub: PagedResultPropertyModel_ = {
  _embedded: [
    {
      id: 'RPT200085',
      created: '2020-03-09T10:01:52.0000000Z',
      modified: '2020-03-09T10:02:00.0000000Z',
      marketingMode: 'sellingAndLetting',
      currency: 'GBP',
      address: {
        buildingName: '',
        buildingNumber: '15',
        line1: 'Example street',
        line2: 'Solihull',
        line3: 'West Midlands',
        line4: '',
        postcode: 'B91 2XX',
        countryId: 'GB',
        geolocation: { latitude: 52.415859, longitude: 1.777338 },
      },
      areaId: 'BRM',
      strapline: '',
      description:
        'We are delighted to offer for sale this EXTENDED THREE BEDROOMED SEMI DETACHED PROPERTY situated ' +
        'in a much sought after residential location of Greasby, having the benefits of two separate entertaining ' +
        ' rooms, morning room, extended kitchen. To the first floor there are three bedrooms, spacious family ' +
        'bathroom, gas central heating gardens front and rear and off road parking.',
      summary: '',
      departmentId: 'G',
      negotiatorId: 'JAS',
      bedrooms: 4,
      receptions: 1,
      bathrooms: 2,
      councilTax: 'A',
      internetAdvertising: true,
      viewingArrangements: 'Accompanied viewings after 3PM only',
      externalArea: { type: 'acres', min: 1, max: 10 },
      internalArea: { type: 'squareFeet', min: 1500, max: 2000 },
      epc: { exempt: false, eer: 45, eerPotential: 71, eir: 53, eirPotential: 81 },
      selling: {
        instructed: '2018-11-18',
        price: 250000,
        qualifier: 'askingPrice',
        status: 'underOffer',
        tenure: { type: 'leasehold', expiry: '2019-05-01' },
        vendorId: 'RPT200085',
      },
      letting: {
        instructed: '2018-11-18',
        availableFrom: '2018-12-26',
        availableTo: '2019-03-23',
        rent: 750,
        rentFrequency: 'monthly',
        term: 'long',
        status: 'toLet',
        landlordId: '',
      },
      type: ['house'],
      style: ['detached'],
      situation: ['garden', 'land', 'patio'],
      parking: ['doubleGarage'],
      age: ['period'],
      locality: ['rural', 'village'],
      rooms: [],
      officeIds: ['OXF', 'SOL'],
      metadata: {},
      _eTag: '"7320C077D9A8F774D4F126470A19FF55"',
      _links: {
        self: { href: '/properties/RPT200085' },
        images: { href: '/propertyImages/?propertyId=RPT200085' },
        documents: { href: '/documents/?ownerType=property&ownerId=RPT200085' },
        offers: { href: '/offers/?propertyId=RPT200085' },
        negotiator: { href: '/negotiators/JAS' },
        offices: { href: '/offices/?id=OXF&id=SOL' },
        department: { href: '/departments/G' },
        vendor: { href: '/vendors/RPT200085' },
        area: { href: '/areas/BRM' },
      },
    },
  ],
  pageNumber: 1,
  pageSize: 25,
  pageCount: 25,
  totalCount: 3072,
  _links: {
    self: { href: '/properties/?PageNumber=1&PageSize=25' },
    first: { href: '/properties/?PageNumber=1&PageSize=25' },
    next: { href: '/properties/?PageNumber=2&PageSize=25' },
    last: { href: '/properties/?PageNumber=123&PageSize=25' },
  },
}
