name: CDK Synth

on:
  pull_request:
    types: ['opened']

jobs:
  check-synth:
    name: CDK Synth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          dir_names_max_depth: 2
          json: true
          quotepath: false

      - name: Fetch config
        run: |
          yarn workspaces foreach --parallel --verbose --since --recursive run conf --name development

      - name: Filter files in packages/ (direct children only)
        id: filter-packages
        run: |
          CHANGED_FOLDERS=$(echo "${{ steps.changed-files.outputs.files }}" | jq -r 'split("\n") | map(select(test("^packages/[^/]+$"))) | join(" ")')
          echo "Changed folders: $CHANGED_FOLDERS"
          echo "::set-output name=changed_folders::$CHANGED_FOLDERS"

      - name: Build
        run: |
          for package in ${{ steps.filter-packages.outputs.changed_folders }}; do
            yarn workspace "$package" run build;
          done

      - name: Remove previous CDK output
        run: |
          for package in ${{ steps.filter-packages.outputs.changed_folders }}; do
            if [jq -r '.scripts.synth' "packages/$package/package.json" -e]; then 
              rm -rf packages/$package/cdk.out; 
            fi 
          done

      - name: Synth
        run: |
          for package in ${{ steps.filter-packages.outputs.changed_folders }}; do
            if [jq -r '.scripts.synth' "packages/$package/package.json" -e]; then
              yarn workspace "$package" synth; 
            fi
          done

      - name: Store changes
        run: |
          DIFF=$(git diff --exit-code)
          echo "DIFF=$DIFF" >> $GITHUB_ENV

      - name: comment
        uses: actions/github-script@v3
        if: ${{ env.DIFF != '' }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.DIFF;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Synth changes have been committed \n\n' + '```' + diff + '```',
            })

      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: synth updates'
