name: CDK Synth

on:
  pull_request:
    types: ['opened']

jobs:
  check-synth:
    name: CDK Synth
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          dir_names: true
          dir_names_max_depth: 2
          json: true
          quotepath: false

      - name: Fetch config
        run: |
          yarn workspaces foreach --parallel --verbose --since --recursive run conf --name development

      - name: Filter files in packages
        id: filter-packages
        run: |
          FILTERED_FOLDERS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | jq -r 'map(select(test("^packages/"))) | map(sub("^packages/"; "")) | unique | join(" ")')
          echo "Changed folders: $FILTERED_FOLDERS"
          echo "CHANGED_FOLDERS=$FILTERED_FOLDERS" >> $GITHUB_ENV

      - name: Build
        run: |
          for package in $FILTERED_FOLDERS; do
            yarn workspace "$package" run build;
          done

      - name: CDK diff
        run: |
          OUTPUT=()
          for package in $FILTERED_FOLDERS; do
            if jq -e '.scripts.synth != null' "packages/$package/package.json" > /dev/null; then
              OUTPUT+=$(yarn workspace $package cdk diff --output packages/$package/cdk.synth)
            fi
          done
          echo $OUTPUT
          echo "CDK_DIFF=$OUTPUT" >> $GITHUB_ENV

      - name: diff
        run: |
          git diff

      # - name: comment
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       const diff = process.env.DIFF;
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'Synth changes have been committed \n\n' + '```' + diff + '```',
      #       })

      # - name: commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: 'chore: synth updates'
