name: Clear cache
on:
  schedule:
    - cron: '0 0 * * 6' # run every staturday

jobs:
  clear-cache:
    name: Clear Actions Cache
    runs-on: ubuntu-latest
    steps:
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
