name: Healthcheck

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install
        run: yarn

      - name: Healthcheck
        run: yarn workspace cloud-alert start --env ENVIRONMENT=production,PACKAGE_NAME=all

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  CYPRESS_SLACK_WEB_HOOK_URL: ${{secrets.CYPRESS_SLACK_WEB_HOOK_URL}}
  CYPRESS_USERNAME: ${{secrets.CYPRESS_USERNAME}}
  CYPRESS_PASSWORD: ${{secrets.CYPRESS_PASSWORD}}
  CYPRESS_WEB_COMPONENTS_X_API_KEY: ${{secrets.CYPRESS_WEB_COMPONENTS_X_API_KEY}}
