name: Build Release Tag

on:
  push:
    tags:
      - '*'

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
  RELEASE_SLACK_WEB_HOOK_URL: ${{secrets.RELEASE_SLACK_WEB_HOOK_URL}}
  CI: true
  IS_RELEASE: true

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set RELEASE_VERSION to process.env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV

      - name: Release version
        run: echo $RELEASE_VERSION

      - name: Checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v2

      - name: Checkout to RELEASE_VERSION
        run: git checkout $RELEASE_VERSION

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up workspace experimental
        run: |
          yarn config set workspaces-experimental true

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure AWS credentials to Production
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Upload Artifact
        run: |
          yarn upload-artifact
