name: Release Note

on:
  repository_dispatch:
    types: [release-note]

jobs:
  release-note:
    runs-on: ubuntu-latest
    steps:
      - name: checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Get yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up workspace experimental
        run: |
          yarn config set workspaces-experimental true

      - name: Install dependencies
        run: |
          yarn add isomorphic-fetch -W

      - name: Generate Release Note
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn release-note ${{ github.event.client_payload.package_name }} ${{ github.event.client_payload.current_tag }} ${{ github.event.client_payload.previous_tag }}
env:
  RELEASE_SLACK_WEB_HOOK_URL: ${{secrets.RELEASE_SLACK_WEB_HOOK_URL}}
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
