name: Release Tag

on:
  push:
    tags:
      - '*'

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SENTRY_AUTH_TOKEN: ${{secrets.SENTRY_AUTH_TOKEN}}
  CI: true
  IS_RELEASE: true

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Set RELEASE_VERSION to process.env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Release version
        run: echo $RELEASE_VERSION

      - name: Checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Checkout to RELEASE_VERSION
        run: git checkout $RELEASE_VERSION

      - name: Setup Node Environment
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Get yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up workspace experimental
        run: |
          yarn config set workspaces-experimental true

      - name: Install dependencies
        run: |
          yarn global add aws-cli serverless@1.59.3
          yarn

      - name: Fetch config
        run: |
          yarn fetch-config development

      - name: Lint
        run: |
          yarn lint

      - name: Build
        run: |
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Upload Artifact
        run: |
          yarn upload-artifact
