name: SMB Pull Request

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - packages/smb/**

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checks out repository to $GITHUB_WORKSPACE
        uses: actions/checkout@v1

      - name: Setup Node Environement
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Test
        run: yarn workspace smb test

      - name: Lint
        run: yarn workspace smb lint

      - name: Build
        run: yarn workspace smb build
