name: Test PR

on:
  pull_request:
    types: ['opened', 'synchronize']

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: ${{secrets.AWS_REGION}}
  CI: true

jobs:
  test-pr:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/4, 2/4, 3/4, 4/4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install
        run: yarn

      - name: Fetch config
        run: |
          yarn workspaces foreach --parallel --verbose --since --recursive run conf --name development

      - name: Test
        run: |
          yarn workspaces foreach --parallel --verbose --interlaced --since --recursive run test --watch=false --ci --forceExit --detectOpenHandles --runInBand --passWithNoTests --shard=${{ matrix.shard }}
